#!/usr/bin/env python3
from __future__ import annotations

"""
fossils - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 2585-3409

Extraction date: 2025-12-10T21:33:20.741333+00:00
Original SHA-256: 0726d788188cc925e02f384fcfabda2515a19d2c571076dc7f35d3208886dcfb
"""

# Standard library imports
import json
import math
import re
import os
import time
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple
import traceback

# Local imports
from Orchestrator.config import SNAPSHOT_INDEX, CFG, VOL_PATH, START_RX, END_RX, SNAP_RE, SNAP_ID_RX
from Orchestrator.volume import read_volume_bytes, read_text_safe

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import CFG, INCLUDE_OTHERS
from Orchestrator.volume import read_volume_bytes


def cap_chars(text: str, max_chars: int) -> str:
    """Truncate text to max_chars, preserving snapshot structure."""
    if len(text) <= max_chars:
        return text
    lines = text.splitlines()
    if not lines:
        return text[:max_chars]
    start_line = lines[0]
    end_line = lines[-1] if lines[-1].startswith("=== END SNAPSHOT") else ""
    body_lines = lines[1:-1] if end_line else lines[1:]
    body = "\n".join(body_lines)
    budget = max_chars - len(start_line) - len(end_line) - 8
    if budget <= 0:
        return start_line[:max_chars]
    trimmed = body[:budget]
    parts = [start_line, trimmed]
    if end_line: parts.append(end_line)
    return "\n".join(parts)


# ── M8 / WI-7a: matched-chunk windowed delivery (window-bound profiles) ──────
# Cloud surfaces deliver snapshots WHOLE (WI-10/M7). The ONE genuinely
# window-bound profile is the on-device phone lean path (6,144-token engine
# window, device-proven). For it, an over-budget snapshot is delivered as a
# window CENTERED on the best-matching chunk (identity from the store's v2
# collapse via retrieve(return_provenance=True)) instead of a blind head
# truncation — the head is usually boilerplate; the matched chunk is why the
# snapshot ranked at all.

_WINDOW_GAP_MARK = "[…]"


def _resolve_active_content_mode() -> str:
    """The active store's content_mode ("full" | "body"), "full" if unavailable.

    Read fresh (config-only, no network) so the windower re-derives against the
    SAME text the store chunked. Never raises — a corrupt/absent store degrades
    to "full" (today's whole-text re-derivation)."""
    try:
        from Orchestrator.embeddings.search import get_active_store  # lazy: import-light
        return get_active_store().content_mode
    except Exception:
        return "full"


def window_snapshot_text(text: str, best_ordinal, budget_chars: int,
                         model_key: Optional[str] = None,
                         content_mode: Optional[str] = None) -> str:
    """Deliver `text` within `budget_chars`, windowed on its best-matched chunk.

    best_ordinal is the store-collapse chunk identity from
    retrieve(return_provenance=True):
      - None / 0  -> no specific window (v1 row, keyword-only candidate, or the
        whole-doc vector won) -> today's head truncation (cap_chars).
      - >= 1      -> chunk (best_ordinal - 1) of the deterministic chunker
        output won: re-derive spans via chunk_snapshot(<source>, model_key) (the
        chunker guarantees verbatim substrings; a multi-chunk group stores the
        whole doc at ordinal 0 and chunker chunk i at ordinal i+1), locate the
        chunk's char range, and expand symmetrically to the budget, snapping
        to line boundaries where cheap.

    content_mode (M14.3c) picks WHAT the re-derivation chunks — it MUST match
    the store that produced best_ordinal, or every ordinal shifts by the
    envelope chunk count and the window points at the wrong passage:
      - None (default) -> resolve from the active store (the ordinals came from
        it); a corrupt/absent store degrades to "full".
      - "full" -> chunk the whole `text` (today's behavior, byte-identical).
      - "body" -> chunk extract_snapshot_content(text) (the Raw-Session-Log
        body — a SUFFIX of `text`), matching a body-mode store's stored chunks.
    Span-location + windowing stay on the FULL `text` either way: the body is a
    suffix, so text.find(body_chunk) still locates it and the START/END marker
    preservation below is unchanged.

    The snapshot's START marker line is always preserved (extract_snap_ids /
    fill_unseen parse provenance from it) and the END marker line is kept when
    present; elided regions are marked with "[…]". Output length <= budget_chars.
    Falls back to cap_chars on ANY re-derivation mismatch (chunker config drift
    since mint, ordinal out of range, span not found) — never raises.
    """
    if len(text) <= budget_chars:
        return text
    if not isinstance(best_ordinal, int) or best_ordinal < 1:
        return cap_chars(text, budget_chars)
    try:
        from Orchestrator.embeddings.chunker import chunk_snapshot  # lazy: keep fossils import-light
        if content_mode is None:
            content_mode = _resolve_active_content_mode()
        # Re-derive against the SAME text the store chunked (M14.3c). In body
        # mode the body is a suffix of `text`, so the located span still lives
        # inside `text` and all the full-text windowing below is unchanged.
        chunk_source = text
        if content_mode == "body":
            body = extract_snapshot_content(text)
            if body:
                chunk_source = body
        chunks = chunk_snapshot(chunk_source, model_key=model_key)
        idx = best_ordinal - 1  # group ordinal i+1 == chunker chunk i
        if len(chunks) <= 1 or idx >= len(chunks):
            return cap_chars(text, budget_chars)  # chunker drift since mint

        # Locate the winning chunk's char span. Chunks are verbatim substrings
        # in document order with strictly increasing start positions, so a
        # sequential find (each from the previous start + 1) pins the right
        # occurrence even when chunk text repeats.
        pos, search_from = -1, 0
        for j in range(idx + 1):
            pos = text.find(chunks[j], search_from)
            if pos == -1:
                return cap_chars(text, budget_chars)  # re-derivation mismatch
            search_from = pos + 1
        c_start, c_end = pos, pos + len(chunks[idx])

        lines = text.splitlines()
        start_line = lines[0] if lines else ""
        end_line = (
            lines[-1]
            if len(lines) > 1 and lines[-1].startswith("=== END SNAPSHOT")
            else ""
        )
        # Reserve frame overhead (marker lines + gap marks + join newlines) so
        # the assembled result stays airtight under budget_chars.
        overhead = (
            len(start_line) + len(end_line) + 2 * (len(_WINDOW_GAP_MARK) + 2) + 4
        )
        body_budget = budget_chars - overhead
        if body_budget <= 0:
            return cap_chars(text, budget_chars)

        span = c_end - c_start
        if span >= body_budget:
            w_start, w_end = c_start, c_start + body_budget
        else:
            pad = (body_budget - span) // 2
            w_start = max(0, c_start - pad)
            w_end = min(len(text), w_start + body_budget)
            w_start = max(0, w_end - body_budget)  # re-anchor when end-clipped

        # Snap to line boundaries where cheap (<=200 chars), never eating into
        # the matched chunk's span.
        if w_start > 0:
            nl = text.find("\n", w_start, min(w_start + 200, c_start))
            if nl != -1:
                w_start = nl + 1
        if w_end < len(text):
            nl = text.rfind("\n", max(w_end - 200, c_end), w_end)
            if nl != -1:
                w_end = nl

        parts = []
        if w_start > 0:
            parts.append(start_line)
            parts.append(_WINDOW_GAP_MARK)
        parts.append(text[w_start:w_end])
        if w_end < len(text):
            parts.append(_WINDOW_GAP_MARK)
            if end_line:
                parts.append(end_line)
        return "\n".join(parts)
    except Exception:
        # Never-raise delivery contract: degrade to head truncation.
        return cap_chars(text, budget_chars)


# ── M14: body-only extraction for RANKING (rerank passages + embed chunks) ────
# Every snapshot text leads with a fixed bookkeeping envelope
# (=== START SNAPSHOT … === / CROSS-FILE BEACON / VOLUME TRACKER / GAUGES) that
# is near-identical across the whole corpus and measurably sabotages ranking:
# reranking on body-only text lifted Vertex recall@10 0.654 -> 0.846 (+29%) /
# MRR 0.352 -> 0.495 (+41%) on 26 labeled same-corpus queries (2026-07-04), and
# the envelope also dilutes every embedding chunk (chunk-0 becomes a
# near-identical boilerplate vector). This helper returns the content-bearing
# region only — the user+AI turns and any distilled summary — so the reranker
# and (M14.3+) the embedder score the meat, not the bookkeeping.

# Content markers, most-specific first. "Raw Session Log" is the primary cut
# (the turns + any Release Notes/summary after them); "SNAPSHOT BODY" is the
# fallback (still drops BEACON/TRACKER/GAUGES, keeps Kernel Index/Provenance).
_CONTENT_MARKERS = ("Raw Session Log", "SNAPSHOT BODY")


def extract_snapshot_content(text: str) -> str:
    """Return the content-bearing portion of a snapshot for RANKING.

    Strips the leading bookkeeping envelope, returning from the first content
    marker onward:
      1. "Raw Session Log" — the user+AI turns plus any Release Notes/summary
         that follows them (dense, keyword-rich content) — the primary cut;
      2. else "SNAPSHOT BODY" — fallback: still drops the worst offenders
         (BEACON/TRACKER/GAUGES) though it keeps the Kernel Index / Context
         Provenance bookkeeping below it;
      3. else the full text unchanged — a snapshot (or non-snapshot text)
         without these markers is NEVER reduced to empty.

    Uses the FIRST occurrence of each marker and returns from the start of that
    marker's line (snapping to line start so an indented marker line still
    drops everything above it). Only the leading envelope is stripped — the
    content region is returned verbatim. Never raises; empty in -> empty out.
    """
    if not text:
        return text
    try:
        for marker in _CONTENT_MARKERS:
            idx = text.find(marker)  # FIRST occurrence
            if idx != -1:
                # Return from the start of the marker's own line. rfind("\n")
                # -> -1 when the marker is on the first line, so +1 yields 0.
                line_start = text.rfind("\n", 0, idx) + 1
                return text[line_start:]
        return text
    except Exception:
        # Never-raise contract: on any unexpected failure, degrade to the full
        # text (ranking on the envelope-inclusive text, never on nothing).
        return text


# ── M15: body-only formatting for DELIVERY (what the MODEL receives) ──────────
# extract_snapshot_content (above) strips for RANKING — it keeps ONLY the Raw
# Session Log region. DELIVERY keeps MORE: a compact attribution header
# ([SNAP-id · UTC date · operator: <op>]) so the model still knows WHICH
# snapshot each memory came from, plus the Context Provenance section (the
# fossil lineage), plus the content (Raw Session Log onward). It still DROPS the
# ~1,000-chars/snapshot bookkeeping envelope the model can't use
# (START / CROSS-FILE BEACON / VOLUME TRACKER / GAUGES / Kernel Index) — measured
# ~5,000 tokens (~8%) of a ~19-snapshot turn. Deliberately a DIFFERENT kept-set
# from the ranking extractor (different consumer, different needs).

# Compact attribution parser: the START line carries UTC date + SNAP-id; GAUGES
# carries OPERATOR. Both are best-effort — a missing/unparseable field is simply
# omitted (never fabricated, never raises).
_DELIVERY_START_RX = re.compile(
    r'^\s*===\s*START SNAPSHOT\s*[—-]\s*UTC\s*(?P<utc>.+?)\s*[—-]\s*'
    r'(?P<snap>SNAP-\d{8}-\d+).*?===\s*$',
    re.M,
)
# Horizontal-whitespace-only around the value: an empty "OPERATOR:" line must
# NOT let \s* swallow the newline and capture the next GAUGES line's value.
_DELIVERY_OPERATOR_RX = re.compile(r'^[ \t]*OPERATOR:[ \t]*(?P<op>\S.*?)[ \t]*$', re.M)
_PROVENANCE_MARKER = "Context Provenance"


def _delivery_attribution(text: str) -> Optional[str]:
    """Best-effort compact attribution header `[SNAP-id · <date> · operator: op]`.

    Returns None when the START line is absent (skip the header entirely). When
    the START line is present, the SNAP-id is always emitted; the date and
    operator are each included only if parseable (omit just the missing field).
    """
    m = _DELIVERY_START_RX.search(text)
    if not m:
        return None
    fields = [m.group("snap")]
    utc = (m.group("utc") or "").strip()
    if utc:
        fields.append(utc)
    op_m = _DELIVERY_OPERATOR_RX.search(text)
    if op_m:
        op = (op_m.group("op") or "").strip()
        if op:
            fields.append(f"operator: {op}")
    return "[" + " · ".join(fields) + "]"


def _delivery_provenance_section(text: str, body: str) -> str:
    """The `Context Provenance` section text, IF it sits above the body cut.

    `body` is a suffix of `text` (extract_snapshot_content returns text[k:]), so
    its start offset is len(text) - len(body). When Context Provenance is above
    that cut (the common Raw-Session-Log case) it is lifted verbatim; when it is
    at/below the cut (the SNAPSHOT-BODY fallback keeps it inside `body`) return
    "" so it is not duplicated. Absent marker -> "".
    """
    idx = text.find(_PROVENANCE_MARKER)
    if idx == -1:
        return ""
    prov_start = text.rfind("\n", 0, idx) + 1  # start of the marker's own line
    body_start = len(text) - len(body)
    if prov_start >= body_start:
        return ""  # already inside the delivered body — don't duplicate
    return text[prov_start:body_start].rstrip()


def format_snapshot_for_delivery(text: str) -> str:
    """Return a snapshot formatted for MODEL DELIVERY (context injection + the
    AI-invoked search tools).

    Emits, in order:
      1. a compact attribution header `[SNAP-id · <UTC date> · operator: <op>]`
         (best-effort; fields omitted individually when unparseable; skipped
         entirely when the START line is absent),
      2. the `Context Provenance` section (the fossil lineage), if present, and
      3. `extract_snapshot_content(text)` — the Raw Session Log onward (the
         user+AI turns plus any Release Notes).

    Drops the bookkeeping envelope the model can't use: START / CROSS-FILE
    BEACON / VOLUME TRACKER / GAUGES / Kernel Index.

    Robust: markers absent (nothing to strip) -> return `text` unchanged; empty
    in -> empty out; never raises. Distinct from extract_snapshot_content, which
    strips for RANKING and keeps ONLY from Raw Session Log.
    """
    if not text:
        return text
    try:
        body = extract_snapshot_content(text)
        # body == text means no leading envelope was stripped (no content marker,
        # or the marker is already the first line) — there is nothing to gain by
        # reformatting, and we never fabricate a header onto un-stripped text.
        if body == text:
            return text
        header = _delivery_attribution(text)
        provenance = _delivery_provenance_section(text, body)
        parts = [p for p in (header, provenance, body) if p]
        return "\n".join(parts)
    except Exception:
        # Never-raise delivery contract: degrade to the full text unchanged.
        return text


def _decode_scored_snapshots(scored, operator: str,
                             window_budget_chars: Optional[int] = None) -> List[str]:
    """Shared decode for the retrieve()-shim retrievers: byte-offset decode of
    the ranked snap_ids (same operator filter + bounds guard both shims have
    always applied), plus OPT-IN matched-chunk windowing (M8/WI-7a).

    `scored` rows are (snap_id, score) or, in provenance mode,
    (snap_id, score, best_ordinal). window_budget_chars=None (every cloud
    caller) delivers decoded texts UNCHANGED; a positive budget windows each
    over-budget text on its best-matched chunk via window_snapshot_text. The
    chunker's model_key is the ACTIVE slug (the ordinals came from the active
    store) — resolved once, config-read only, no provider/network call.
    """
    index = load_snapshot_index()
    vol_bytes = read_volume_bytes(VOL_PATH)

    model_key = None
    content_mode = "full"
    if window_budget_chars is not None:
        try:
            from Orchestrator.embeddings.store import get_active_slug
            model_key = get_active_slug()
        except Exception:
            model_key = None  # tokenization floor still windows correctly
        # Resolve the active store's content_mode ONCE (M14.3c) and thread it
        # to every window call — the ordinals came from this store, so the
        # windower must re-chunk the same (full | body) text. Cheap + never
        # raises (degrades to "full").
        content_mode = _resolve_active_content_mode()

    results = []
    for row in scored:
        snap_id = row[0]
        best_ordinal = row[2] if len(row) > 2 else None
        meta = index.get(snap_id)
        if not meta:
            continue
        if operator and operator != "system" and meta.get("operator") != operator:
            continue
        start = meta["byte_start"]
        end = meta["byte_end"]
        if start < len(vol_bytes) and end <= len(vol_bytes):
            text = vol_bytes[start:end].decode('utf-8', errors='replace')
            if window_budget_chars is not None:
                text = window_snapshot_text(
                    text, best_ordinal, window_budget_chars, model_key,
                    content_mode=content_mode,
                )
            results.append(text)
    return results


def hybrid_retrieve(vol_txt: str, query: str, k: int = 3, operator: str = "",
                    window_budget_chars: Optional[int] = None) -> List[str]:
    """Hybrid retrieval — thin shim over the canonical retrieve() (Phase 3b).

    Ranking now lives entirely in Orchestrator.retrieval.retrieve(): RRF fusion of
    keyword + semantic candidates, a mild recency tie-break, MMR diversity, and a
    junk-floor instead of a hard threshold. This INTENTIONALLY changes the old
    40/60 weighted-sum ranking — that is the point of Phase 3b. This function is
    now just retrieve() + byte-offset text decode (the SAME return type as before:
    a list of decoded snapshot texts, highest-ranked first).

    `vol_txt` is retained for signature/caller compatibility but is UNUSED —
    retrieve() reads VOL_PATH itself (and embeds the query) internally.

    window_budget_chars (keyword-use, M8/WI-7a): None (every cloud caller —
    default) delivers decoded texts WHOLE, byte-identical to before. A positive
    budget is the window-bound-profile path (the on-device search_snapshots
    executor): each over-budget text is delivered as a window centered on its
    best-matched chunk (see window_snapshot_text); keyword-only candidates
    have no chunk identity and head-truncate.
    """
    # Lazy import: retrieval.py imports from fossils at module top, so importing
    # retrieve at fossils' module top would create an import cycle.
    from Orchestrator.retrieval import retrieve

    scored = retrieve(
        query, operator=operator, k=k, include_keyword=True,
        return_provenance=window_budget_chars is not None,
    )

    # Decode ONLY the result snapshots' bytes (same operator filter + byte-offset
    # guard as before; a snap_id that is absent/operator-mismatched/out-of-bounds
    # is skipped).
    results = _decode_scored_snapshots(scored, operator, window_budget_chars)

    print(f"[HYBRID] retrieve() -> {len(results)} results")
    return results


def semantic_retrieve(query: str, operator: str = "", k: int = 15, threshold: float = 0.60,
                      *, window_budget_chars: Optional[int] = None) -> List[str]:
    """Pure-semantic retrieval — a THIN SHIM over the canonical retrieve() (Phase 3b-2).

    This is the shared semantic entry for the per-turn context (cloud chat/voice AND
    the on-device lean profile via build_fossil_context), the Computer-Use context,
    and tasks. Routing it through retrieve() unifies ALL of them on the one canonical
    recency-aware ranker (RRF + mild recency tie-break + MMR diversity + junk-floor,
    top-k). This INTENTIONALLY makes the per-turn semantic context recency-aware
    instead of a hard >= threshold filter — that is the point of Phase 3b-2 (pre-
    validated by the Phase-5 golden set: recency surfaces recent work AND single-event
    facts still rank #1).

    `include_keyword=False` is REQUIRED: every caller of semantic_retrieve already has
    its OWN separate keyword channel, so the semantic channel must stay pure-semantic
    (+recency+MMR) to avoid double-counting the keyword signal.

    Args:
        query: Search query text
        operator: Filter by operator (empty string / "system" = all operators)
        k: Maximum number of results to return
        threshold: RETAINED for signature/caller compatibility only. It is now
            UNUSED and superseded by retrieve()'s own junk_floor + top-k (Phase 3).
            Display/log-only: the three callers feed it from active_threshold
            for their [CONTEXT]/[SEMANTIC] log lines; the ranking floor lives
            in retrieval.py's junk-floor resolution — global
            [retrieval] junk_floor or, flag-gated, the per-model registry
            junk_floor (M9/WI-3). Kept, not deleted: three live call sites,
            zero behavior value — removal churn > benefit this cycle.
        window_budget_chars: keyword-only (M8/WI-7a). None (every cloud
            caller — default) delivers decoded texts WHOLE, byte-identical to
            before. A positive budget is the window-bound-profile path (the
            on-device phone lean profile via build_fossil_context's local
            CAP): each over-budget text is delivered as a window centered on
            its best-matched chunk instead of blind head truncation (see
            window_snapshot_text). Ranking is untouched either way.

    Returns:
        List of decoded snapshot texts (SAME return type as before), highest-ranked
        first.
    """
    # Lazy import: retrieval.py imports from fossils at module top, so importing
    # retrieve at fossils' module top would create an import cycle.
    from Orchestrator.retrieval import retrieve

    scored = retrieve(
        query, operator=operator, k=k, include_keyword=False,
        return_provenance=window_budget_chars is not None,
    )

    # Decode ONLY the result snapshots' bytes (same operator filter + byte-offset
    # guard as the old body / hybrid_retrieve; a snap_id that is absent/operator-
    # mismatched/out-of-bounds is skipped).
    results = _decode_scored_snapshots(scored, operator, window_budget_chars)

    print(f"[SEMANTIC] retrieve() -> {len(results)} results")
    return results


# -----------------------------------------------------------------------------
# Retrieval
# -----------------------------------------------------------------------------
# Stop words to filter out (common English words that add noise)
STOP_WORDS = set([
    # Articles & determiners
    'the', 'a', 'an', 'this', 'that', 'these', 'those',
    # Pronouns
    'i', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them',
    'my', 'your', 'his', 'her', 'its', 'our', 'their', 'mine', 'yours', 'hers', 'ours', 'theirs',
    'myself', 'yourself', 'himself', 'herself', 'itself', 'ourselves', 'themselves',
    # Prepositions
    'in', 'on', 'at', 'to', 'for', 'with', 'from', 'by', 'about', 'into', 'through',
    'after', 'before', 'between', 'under', 'over', 'above', 'below',
    # Conjunctions
    'and', 'or', 'but', 'because', 'if', 'when', 'while', 'although', 'though', 'unless',
    # Verbs (common auxiliary & copula)
    'be', 'is', 'am', 'are', 'was', 'were', 'been', 'being',
    'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing',
    'will', 'would', 'shall', 'should', 'can', 'could', 'may', 'might', 'must',
    # Question words
    'what', 'where', 'when', 'why', 'how', 'who', 'which', 'whose', 'whom',
    # Common verbs
    'get', 'got', 'gotten', 'go', 'going', 'gone', 'went', 'make', 'made', 'making',
    'take', 'took', 'taken', 'taking', 'come', 'came', 'coming', 'see', 'saw', 'seen', 'seeing',
    'know', 'knew', 'known', 'knowing', 'think', 'thought', 'thinking', 'look', 'looked', 'looking',
    'want', 'wanted', 'wanting', 'give', 'gave', 'given', 'giving', 'use', 'used', 'using',
    'find', 'found', 'finding', 'tell', 'told', 'telling', 'ask', 'asked', 'asking',
    'work', 'worked', 'working', 'seem', 'seemed', 'seeming', 'feel', 'felt', 'feeling',
    'try', 'tried', 'trying', 'leave', 'left', 'leaving', 'call', 'called', 'calling',
    # Adverbs
    'not', 'no', 'yes', 'so', 'just', 'now', 'then', 'there', 'here', 'up', 'down', 'out',
    'only', 'also', 'back', 'even', 'well', 'still', 'too', 'very', 'really', 'quite',
    'rather', 'much', 'more', 'most', 'less', 'least', 'too', 'enough', 'already', 'yet',
    # Quantifiers
    'all', 'some', 'any', 'many', 'few', 'several', 'both', 'each', 'every', 'either', 'neither',
    'one', 'two', 'three', 'first', 'second', 'last', 'next', 'other', 'another',
    # Filler words & discourse markers
    'thing', 'stuff', 'yeah', 'ok', 'okay', 'right', 'actually', 'basically', 'literally',
    'like', 'guess', 'maybe', 'perhaps', 'probably', 'sure', 'anyway', 'whatever',
    # Time references
    'time', 'day', 'year', 'today', 'yesterday', 'tomorrow',
    # Common nouns (too generic)
    'people', 'person', 'man', 'woman', 'child', 'way', 'place', 'thing',
    # Others
    'of', 'as', 'say', 'said', 'says', 'saying', 'something', 'anything', 'everything', 'nothing',
    # Contraction fragments (from apostrophe splitting)
    't', 's', 're', 've', 'll', 'd', 'm',
    'don', 'doesn', 'didn', 'isn', 'aren', 'wasn', 'weren', 'hasn', 'haven', 'hadn',
    'won', 'wouldn', 'shouldn', 'couldn', 'mightn', 'mustn', 'needn', 'shan', 'ain'
])

# Technical terms that should be weighted more heavily in searches
TECHNICAL_TERMS = set([
    'byte', 'bytes', 'index', 'snapshot', 'snap', 'error', 'warning',
    'debug', 'fix', 'bug', 'issue', 'retrieve', 'retrieval', 'context',
    'offset', 'character', 'string', 'decode', 'encode', 'utf',
    'cache', 'file', 'read', 'write', 'mint', 'fossil', 'operator',
    'api', 'endpoint', 'function', 'method', 'class', 'variable',
    'log', 'trace', 'stack', 'exception', 'timeout', 'race', 'condition',
    'lock', 'thread', 'async', 'sync', 'database', 'query', 'sql',
    'hash', 'sha', 'checksum', 'verify', 'validate', 'parse', 'regex'
])

def fossil_operator(text: str) -> str:
    m = OP_RX.search(text or "")
    return (m.group(1).strip() if m else "")

def filter_by_operator(fossils: List[str], op: str) -> List[str]:
    if not fossils: return []
    keep = []
    for f in fossils:
        op_in_fossil = fossil_operator(f)
        if op_in_fossil == op:
            keep.append(f)
        elif INCLUDE_OTHERS and not op_in_fossil:
            keep.append(f)
    return keep

# -----------------------------------------------------------------------------
# Snapshot Index Management (Byte Offset Optimization)
# -----------------------------------------------------------------------------
# In-memory index cache — avoids re-parsing 254MB JSON on every call
_index_cache: Optional[Dict[str, Dict[str, Any]]] = None
_index_cache_mtime: float = 0.0

# Schema version sentinel (T1 / audit M9). Bump when the per-snapshot dict
# shape in snapshot_index.json changes in a way readers can't tolerate.
# Lives in a SEPARATE file (Manifest/schema_version.json) because the index
# itself is a flat dict mapping snap_id → metadata — adding a sibling key
# would break every iterator (.items(), len(), keys(), .values()) that
# assumes top-level entries are snapshots.
#
# Increment by 1 whenever the schema changes. Add an upgrade path here when
# you do — currently bumping version triggers a full rebuild from the volume
# file (rebuild_snapshot_index preserves existing embeddings).
CURRENT_SCHEMA_VERSION = 1
SCHEMA_VERSION_FILE = SNAPSHOT_INDEX.parent / "schema_version.json"


def read_schema_version() -> int:
    """Return the schema version recorded in Manifest/schema_version.json,
    or 0 if the file is missing/unreadable (treated as "pre-versioning"
    install — caller should rebuild)."""
    try:
        if not SCHEMA_VERSION_FILE.exists():
            return 0
        with open(SCHEMA_VERSION_FILE, "r", encoding="utf-8") as f:
            return int(json.load(f).get("schema_version", 0))
    except Exception:
        return 0


def write_schema_version(version: int = CURRENT_SCHEMA_VERSION) -> None:
    """Persist the schema version. Called after a successful rebuild or
    after schema-aware code has confirmed the on-disk index matches the
    current expected shape."""
    try:
        SCHEMA_VERSION_FILE.parent.mkdir(parents=True, exist_ok=True)
        tmp = SCHEMA_VERSION_FILE.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump({"schema_version": int(version)}, f)
        os.replace(tmp, SCHEMA_VERSION_FILE)
    except Exception as e:
        print(f"[WARNING] Failed to write schema_version: {e}")


def load_snapshot_index() -> Dict[str, Dict[str, Any]]:
    """Load the snapshot index, using in-memory cache when possible.

    The cache is invalidated when the file's mtime changes (i.e., after save).
    This avoids parsing 254MB of JSON on every search/mint/status call.
    """
    global _index_cache, _index_cache_mtime
    try:
        if not SNAPSHOT_INDEX.exists():
            return {}
        current_mtime = SNAPSHOT_INDEX.stat().st_mtime
        if _index_cache is not None and current_mtime == _index_cache_mtime:
            return _index_cache
        with open(SNAPSHOT_INDEX, 'r', encoding='utf-8') as f:
            _index_cache = json.load(f)
        _index_cache_mtime = current_mtime
        return _index_cache
    except Exception as e:
        print(f"[WARNING] Failed to load snapshot index: {e}")
    return {}


def get_snapshot_by_id(snap_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve a specific snapshot by its ID.

    Args:
        snap_id: Snapshot ID (e.g., "SNAP-20251207-1234")

    Returns:
        Dict with 'content', 'metadata' (operator, timestamp, type), or None if not found
    """
    index = load_snapshot_index()

    if snap_id not in index:
        return None

    meta = index[snap_id]
    vol_bytes = read_volume_bytes(VOL_PATH)

    start = meta.get("byte_start", 0)
    end = meta.get("byte_end", 0)

    if start >= len(vol_bytes) or end > len(vol_bytes):
        return None

    snap_bytes = vol_bytes[start:end]
    content = snap_bytes.decode('utf-8', errors='replace')

    return {
        "snap_id": snap_id,
        "content": content,
        "metadata": {
            "operator": meta.get("operator"),
            "timestamp": meta.get("timestamp"),
            "type": meta.get("type", "normal"),
            "byte_start": start,
            "byte_end": end
        }
    }


def save_snapshot_index(index: Dict[str, Dict[str, Any]]):
    """Save the snapshot index to disk atomically and update the in-memory cache."""
    global _index_cache, _index_cache_mtime
    try:
        SNAPSHOT_INDEX.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = SNAPSHOT_INDEX.with_suffix('.tmp')
        with open(tmp_path, 'w', encoding='utf-8') as f:
            json.dump(index, f, indent=2)
        os.replace(tmp_path, SNAPSHOT_INDEX)
        # Update cache directly — avoid re-reading the file we just wrote
        _index_cache = index
        _index_cache_mtime = SNAPSHOT_INDEX.stat().st_mtime
    except Exception as e:
        print(f"[ERROR] Failed to save snapshot index: {e}")

def rebuild_snapshot_index() -> Dict[str, Dict[str, Any]]:
    """Rebuild the entire snapshot index by scanning the volume file.

    CRITICAL: Works directly on BYTES using byte-compiled regexes so that
    byte offsets are true file positions — no O(n²) char-to-byte conversion.

    IMPORTANT: Preserves existing embeddings when rebuilding to avoid losing
    expensive embedding data.
    """
    print("[INDEX] Rebuilding snapshot index from volume file...")
    start_time = time.time()

    # Load existing index to preserve embeddings
    old_index = load_snapshot_index()
    embeddings_preserved = 0

    index = {}
    if not VOL_PATH.exists():
        return index

    # Read as BYTES — regex directly on bytes gives true byte offsets (O(n))
    vol_bytes = read_volume_bytes(VOL_PATH)

    # Byte-level regexes for START and END markers
    # START captures snap_id and UTC timestamp (always present and consistent)
    START_RX_B = re.compile(rb'=== START SNAPSHOT \xe2\x80\x94 UTC (?P<utc>\d{4}-\d{2}-\d{2}T[\d:]+Z) \xe2\x80\x94 (?P<snap>SNAP-\d{8}-\d+)')
    # END uses snap_id-specific match to avoid cross-boundary jumps
    OP_RX_B = re.compile(rb'OPERATOR:\s*([^\n]+)')

    pos = 0
    count = 0

    while True:
        m_start = START_RX_B.search(vol_bytes, pos)
        if not m_start:
            break
        snap_id = m_start.group("snap").decode('utf-8')
        utc = m_start.group("utc").decode('utf-8')

        # Search for THIS snapshot's specific END marker
        end_pattern = rb'=== END SNAPSHOT \xe2\x80\x94 ' + re.escape(snap_id.encode()) + rb'.*?==='
        m_end = re.search(end_pattern, vol_bytes[m_start.end():m_start.end() + 200000])
        if not m_end:
            # Skip this snapshot — no matching END found
            pos = m_start.end()
            continue

        # Byte positions — m_end is relative to the slice, convert to absolute
        byte_start = m_start.start()
        byte_end = m_start.end() + m_end.end()

        # Extract operator from snapshot bytes
        snap_bytes = vol_bytes[byte_start:byte_end]
        operator = "Unknown"
        op_match = OP_RX_B.search(snap_bytes)
        if op_match:
            operator = op_match.group(1).strip().decode('utf-8', errors='replace')

        # Detect if this is a checkpoint snapshot
        snap_type = "checkpoint" if b"[CHECKPOINT]" in snap_bytes else "normal"

        index[snap_id] = {
            "byte_start": byte_start,
            "byte_end": byte_end,
            "operator": operator,
            "timestamp": utc,
            "type": snap_type
        }

        # Preserve embedding from old index if it exists
        if snap_id in old_index and "embedding" in old_index[snap_id]:
            index[snap_id]["embedding"] = old_index[snap_id]["embedding"]
            embeddings_preserved += 1

        pos = byte_end
        count += 1

        if count % 500 == 0:
            print(f"[INDEX] Processed {count} snapshots...")

    save_snapshot_index(index)
    # T1 / audit M9: record schema version after a successful rebuild so the
    # next startup check can fast-path past the rebuild trigger.
    write_schema_version(CURRENT_SCHEMA_VERSION)
    elapsed = time.time() - start_time
    print(f"[INDEX] Rebuilt index with {count} snapshots in {elapsed:.2f}s")
    if embeddings_preserved > 0:
        print(f"[INDEX] Preserved {embeddings_preserved} embeddings from previous index")
    return index

def update_snapshot_index(snap_id: str, byte_start: int, byte_end: int, operator: str, timestamp: str, snap_type: str = "normal", embedding: Optional[List[float]] = None, media_artifacts: Optional[List[Dict[str, Any]]] = None, chunk_vectors: Optional[List[List[float]]] = None):
    """Update the index with a newly minted snapshot, including optional embedding and media artifacts.

    Args:
        snap_id: Snapshot ID (e.g., SNAP-20260123-456)
        byte_start: Starting byte offset in volume file
        byte_end: Ending byte offset in volume file
        operator: Operator/user name
        timestamp: UTC timestamp
        snap_type: Type of snapshot ("normal", "checkpoint", etc.)
        embedding: Optional whole-snapshot embedding vector — appended to the
            ACTIVE VectorStore (Manifest/embeddings/) when it is schema 1,
            NEVER stored inline in the JSON entry (post-transcode indexes
            stay slim)
        chunk_vectors: Optional chunk-group vectors (M6c) — appended to the
            ACTIVE VectorStore as ONE contiguous group in document order when
            it is schema 2. Mutually shaped with `embedding`: the vector-block
            schema guard below validates whichever arrived against the
            store's CURRENT schema at append time (audit A4) and drops a
            mismatch for the catch-up loop to re-embed.
        media_artifacts: Optional list of media artifact metadata dicts containing:
            - type: "image", "video", or "music"
            - url: URL path (e.g., /ui/uploads/sunset-over-mountains_abc123.png)
            - task_id: Task ID that generated this media
            - prompt: Prompt used for generation
            - model: Model used for generation
            - aspect_ratio: For images/videos
            - resolution: For images/videos
            - created_at: ISO timestamp
    """
    try:
        print(f"[INDEX] Updating index with {snap_id} (operator: {operator}, type: {snap_type})")
        index = load_snapshot_index()
        print(f"[INDEX] Loaded existing index with {len(index)} entries")
        index[snap_id] = {
            "byte_start": byte_start,
            "byte_end": byte_end,
            "operator": operator,
            "timestamp": timestamp,
            "type": snap_type
        }

        # Vector write seam (pluggable embeddings): vectors go to the ACTIVE
        # binary store, never into the JSON entry. A mint must NEVER fail
        # because of the vector layer — every store-side error below is
        # logged and the vector dropped (the migration job's catch-up loop
        # re-embeds missing ids later, keyed on store.missing()).
        #
        # M6c schema guard (audit A4): the payload shape is validated against
        # the store's CURRENT schema at APPEND time — covering the race where
        # the active store changed between embed and append, in BOTH
        # directions. A whole-snapshot vector must never masquerade as a
        # 1-chunk group in a schema-2 store, and chunk vectors must never
        # land as a bogus single row in a v1 store.
        if embedding is not None or chunk_vectors:
            store = None
            schema = 1
            try:
                # Lazy import (monitoring.py's delegate pattern): fossils is
                # imported very early at startup, before the embeddings stack.
                from Orchestrator.embeddings.search import get_active_store
                store = get_active_store()
                schema = store.schema
            except Exception as e:
                store = None
                print(f"[INDEX] active store unavailable; snapshot {snap_id} minted without vector: {e}")
            if store is not None and schema == 2:
                if not chunk_vectors:
                    # Bare whole-snapshot vector vs chunked store: DROP.
                    # (Mirror of the dims-mismatch race branch — catch-up
                    # re-embeds this snapshot as a proper chunk group.)
                    print(f"[EMBEDDING] {snap_id}: whole-snapshot vector vs chunked store — dropped; catch-up re-embeds")
                elif any(len(vec) != store.dims for vec in chunk_vectors):
                    # Cutover race: chunks embedded under the old model, store
                    # swapped before this index update landed. All-or-nothing:
                    # a partial group must never exist (audit A3).
                    bad = next(len(vec) for vec in chunk_vectors if len(vec) != store.dims)
                    print(f"[INDEX] chunk vector has {bad} dims but active store expects {store.dims}; snapshot {snap_id} minted without vector (catch-up re-embeds it)")
                else:
                    try:
                        # append invalidates the store's matrix cache; next
                        # search re-reads the file (page-cache warm, tens of ms)
                        rows = store.append_group(snap_id, chunk_vectors)
                        print(f"[INDEX] Stored {len(chunk_vectors)}-chunk group for {snap_id} in {store.slug} store ({rows} rows written)")
                    except Exception as e:
                        print(f"[INDEX] store append failed; snapshot {snap_id} minted without vector: {e}")
            elif store is not None:
                if embedding is None:
                    # Chunk vectors vs whole-snapshot (v1) store: DROP —
                    # chunk_vectors[0] is NOT a whole-snapshot embedding.
                    print(f"[EMBEDDING] {snap_id}: chunk vectors vs whole-snapshot store — dropped; catch-up re-embeds")
                elif len(embedding) != store.dims:
                    # Cutover race: embedding generated under the old model,
                    # store swapped before this index update landed.
                    print(f"[INDEX] embedding has {len(embedding)} dims but active store expects {store.dims}; snapshot {snap_id} minted without vector (catch-up re-embeds it)")
                else:
                    try:
                        # append invalidates the store's matrix cache; next
                        # search re-reads the file (page-cache warm, tens of ms)
                        store.append(snap_id, embedding)
                        print(f"[INDEX] Stored embedding for {snap_id} in {store.slug} store ({len(embedding)} dimensions)")
                    except Exception as e:
                        print(f"[INDEX] store append failed; snapshot {snap_id} minted without vector: {e}")

        # Add media artifacts if provided
        if media_artifacts:
            index[snap_id]["media_artifacts"] = media_artifacts
            print(f"[INDEX] Stored {len(media_artifacts)} media artifact(s) for {snap_id}")

        save_snapshot_index(index)
        print(f"[INDEX] Successfully updated index with {snap_id}, now {len(index)} entries")
    except Exception as e:
        print(f"[ERROR] Failed to update snapshot index: {e}")
        import traceback
        traceback.print_exc()

def split_snapshots(vol_txt: str) -> List[Tuple[str, int, int]]:
    snaps = []
    pos = 0
    while True:
        m_start = START_RX.search(vol_txt, pos)
        if not m_start:
            break
        m_end = END_RX.search(vol_txt, m_start.end())
        if not m_end:
            break
        s = m_start.start()
        e = m_end.end()
        snaps.append((vol_txt[s:e], s, e))
        pos = e
    return snaps


def split_snapshot_spans(vol_txt: str) -> List[Tuple[int, int]]:
    """Like :func:`split_snapshots` but returns only the (start, end) CHAR offsets,
    NOT a decoded substring per snapshot.

    Same boundary logic (same START_RX/END_RX scan, same ``pos = e`` advance) so the
    spans are byte-for-byte the (s, e) that split_snapshots would produce. Callers
    that scan the whole corpus but only need a handful of substrings can slice
    ``vol_txt[s:e]`` on demand instead of materializing ~7176 substrings (~89 MB).
    """
    spans = []
    pos = 0
    while True:
        m_start = START_RX.search(vol_txt, pos)
        if not m_start:
            break
        m_end = END_RX.search(vol_txt, m_start.end())
        if not m_end:
            break
        s = m_start.start()
        e = m_end.end()
        spans.append((s, e))
        pos = e
    return spans

def extract_snap_ids(blocks: List[str]) -> List[str]:
    """Extract snapshot IDs from snapshot text blocks.

    IMPORTANT: Must extract from START marker, not just any SNAP-ID occurrence!
    Snapshots contain provenance references to other snapshots, so a simple
    SNAP_ID_RX.search() will find the wrong ID (from provenance, not header).
    """
    out: List[str] = []
    for b in blocks or []:
        # Extract from START marker specifically
        m = START_RX.search(b)
        if m:
            out.append(m.group("snap"))
        else:
            # Fallback to simple pattern if no START marker (shouldn't happen)
            m = SNAP_ID_RX.search(b)
            if m:
                out.append(m.group(1))
    return out

def get_recent_fossils_for_operator(vol_txt: str, op: str, count: int, cap_chars_each: Optional[int]) -> List[str]:
    """Get recent snapshots for an operator. Uses index if available for O(1) access.

    IMPORTANT: Byte offsets in the index are BYTE positions, not character positions.
    We must read the file as bytes, slice using byte offsets, then decode individual snapshots.

    Special case: "system" operator can see ALL snapshots from all operators.
    This is needed for outbound calls where the AI needs context from prior conversations.

    cap_chars_each: per-snapshot char cap, or None/<=0 for UNCAPPED (whole
    snapshots). Since WI-10 (M7) all CLOUD delivery passes None — caps exist
    only at the embedding layer; the remaining capped consumers are the local
    phone lean profile ([context] max_fossil_chars) and the checkpoint
    compressor's source window (checkpoint.py).
    """
    index = load_snapshot_index()

    if index:
        # Use index for fast retrieval - MUST use bytes for byte-offset slicing
        # Read file as bytes to allow proper byte-offset indexing
        vol_bytes = read_volume_bytes(VOL_PATH)

        # Filter by operator - "system" sees all operators
        if op == "system":
            matching = [(snap_id, meta) for snap_id, meta in index.items()]
        else:
            matching = [(snap_id, meta) for snap_id, meta in index.items() if meta.get("operator") == op]

        # Sort by snap_id with proper numeric comparison on date and sequence
        def snapshot_sort_key(snap_id: str) -> tuple:
            """Parse SNAP-YYYYMMDD-NNN and return (date_int, seq_int) for proper sorting."""
            try:
                parts = snap_id.split('-')
                date_part = int(parts[1]) if len(parts) > 1 else 0
                seq_part = int(parts[2]) if len(parts) > 2 else 0
                return (date_part, seq_part)
            except (ValueError, IndexError):
                # Fallback for malformed IDs: sort them at the beginning
                return (0, 0)

        matching.sort(key=lambda x: snapshot_sort_key(x[0]))

        # Validate index consistency
        if matching:
            max_byte_end = max(meta["byte_end"] for _, meta in matching)
            if max_byte_end > len(vol_bytes):
                print(f"[WARNING] Index expects file to be at least {max_byte_end} bytes, but vol_bytes is only {len(vol_bytes)} bytes")

        # Get all snapshots (no limit)
        recent = matching[:]
        texts = []

        for snap_id, meta in recent:
            start = meta["byte_start"]
            end = meta["byte_end"]
            # Direct byte-range read using BYTE offsets on BYTES
            if start < len(vol_bytes) and end <= len(vol_bytes):
                snap_bytes = vol_bytes[start:end]
                # Decode the snapshot bytes to text
                snap_text = snap_bytes.decode('utf-8', errors='replace')

                # Verify snapshot integrity
                m = START_RX.search(snap_text)
                if m:
                    extracted_id = m.group("snap")
                    if extracted_id != snap_id:
                        print(f"[ERROR] Index mismatch! Expected {snap_id} at bytes {start}-{end}, but got {extracted_id}")
                else:
                    print(f"[ERROR] No START marker found for {snap_id} at bytes {start}-{end}")

            elif start < len(vol_bytes):
                # Partial snapshot available
                snap_bytes = vol_bytes[start:]
                snap_text = snap_bytes.decode('utf-8', errors='replace')
                print(f"[WARNING] Snapshot {snap_id} byte_end ({end}) exceeds vol_bytes length ({len(vol_bytes)}), text may be incomplete")
            else:
                snap_text = ""
                print(f"[WARNING] Snapshot {snap_id} byte_start ({start}) exceeds vol_bytes length ({len(vol_bytes)})")

            texts.append(cap_chars(snap_text, cap_chars_each) if cap_chars_each and cap_chars_each > 0 else snap_text)

        final_texts = texts[-count:] if count > 0 else texts
        return final_texts
    else:
        # Fallback to old method if index not available
        snaps = split_snapshots(vol_txt)
        texts = [t for (t, _s, _e) in snaps[:]]  # Get all snapshots (no limit)
        if cap_chars_each and cap_chars_each > 0:
            texts = [cap_chars(t, cap_chars_each) for t in texts]
        texts = filter_by_operator(texts, op)
        return texts[-count:] if count>0 else texts

def _simple_stem(word: str) -> str:
    """Improved suffix-based stemming for common English patterns.

    More conservative approach that avoids over-stemming and creating odd stems.
    """
    # Don't stem very short words (< 4 chars)
    if len(word) < 4:
        return word

    # Protected words that should never be stemmed
    protected = {
        'snapshot', 'checkpoint', 'error', 'index', 'bytes', 'fossil',
        'endpoint', 'database', 'async', 'status', 'process'
    }
    if word in protected:
        return word

    # Handle suffixes in order of specificity (longest first to avoid conflicts)
    # Only stem if the root will be meaningful (>= 4 chars)
    suffixes = [
        ('ication', 'ify'),   # modification → modify
        ('ational', 'ate'),   #ational → nate
        ('ization', 'ize'),   # realization → realize
        ('ousness', 'ous'),   # consciousness → conscious
        ('fulness', 'ful'),   # usefulness → useful
        ('iveness', 'ive'),   # effectiveness → effective
        ('ation', 'ate'),     # creation → create
        ('ition', 'it'),      # condition → condit (but protected above)
        ('ement', ''),        # replacement → replac
        ('ment', ''),         # deployment → deploy
        ('ness', ''),         #ingness → ing
        ('ity', ''),          # complexity → complex
        ('ful', ''),          # successful → success
        ('less', ''),         # endless → end
        ('ing', ''),          # indexing → index
        ('ed', ''),           # indexed → index
        ('es', ''),           # indexes → index
        ('s', ''),            # snapshots → snapshot (but be careful)
    ]

    for suffix, replacement in suffixes:
        if word.endswith(suffix) and len(word) > len(suffix) + 2:
            # Calculate what the stem would be
            stem_base = word[:-len(suffix)]
            stemmed = stem_base + replacement

            # Only apply stemming if:
            # 1. The stem is at least 3 characters
            # 2. For 's' suffix, only remove if the word is plural (ends in 's' but not 'ss', 'us', 'is')
            if suffix == 's':
                # Don't remove 's' from: class, bus, this, analysis, etc.
                if word.endswith(('ss', 'us', 'is', 'as', 'os')) or len(stem_base) < 3:
                    continue

            if len(stemmed) >= 3:
                return stemmed

    return word

def _extract_terms(query: str) -> List[str]:
    """Extract meaningful terms from query, filtering stop words and applying stemming."""
    # Use word boundary regex to preserve complete words (including apostrophes and hyphens)
    # This prevents "don't" from becoming ["don", "t"]
    words = [w.lower() for w in re.findall(r"\b[a-zA-Z][a-zA-Z0-9''\-]*[a-zA-Z0-9]\b|\b[a-zA-Z]\b", query or "")]

    # Filter out stop words and very short words (< 3 chars after removing punctuation)
    filtered = []
    for w in words:
        # Remove trailing/leading apostrophes and hyphens for comparison
        clean_word = w.strip("'-'")

        # Skip if it's a stop word or too short
        if clean_word not in STOP_WORDS and len(clean_word) >= 3:
            filtered.append(clean_word)

    # Apply simple stemming to normalize terms
    stemmed = [_simple_stem(w) for w in filtered]

    # Remove duplicates while preserving order
    seen = set()
    unique_terms = []
    for term in stemmed:
        if term not in seen and term not in STOP_WORDS:
            seen.add(term)
            unique_terms.append(term)

    return unique_terms

def _generate_ngrams(query: str, n: int = 2) -> List[str]:
    """Generate n-grams (phrases) from the query for exact phrase matching.

    Filters out n-grams that consist entirely of stop words or contain mostly stop words.
    """
    # Extract words using the same regex as _extract_terms to be consistent
    words = [w.lower() for w in re.findall(r"\b[a-zA-Z][a-zA-Z0-9''\-]*[a-zA-Z0-9]\b|\b[a-zA-Z]\b", query or "")]

    ngrams = []
    for i in range(len(words) - n + 1):
        phrase_words = words[i:i+n]
        phrase = " ".join(phrase_words)

        # Clean words for stop word checking
        clean_words = [w.strip("'-'") for w in phrase_words]

        # Count non-stop words in the phrase
        non_stop_count = sum(1 for w in clean_words if w not in STOP_WORDS and len(w) >= 3)

        # Only keep phrases that:
        # 1. Have at least one meaningful (non-stop) word
        # 2. Don't consist entirely of stop words
        # 3. Have reasonable length (>= 6 characters)
        if non_stop_count >= 1 and len(phrase) >= 6:
            # Further filter: for bigrams, require at least 1 non-stop word
            # For trigrams, require at least 2 non-stop words
            if (n == 2 and non_stop_count >= 1) or (n >= 3 and non_stop_count >= 2):
                ngrams.append(phrase)

    return ngrams

def _streaming_tfidf_scores(decode_lc, num_docs: int, terms: List[str]) -> List[float]:
    """Shared streaming base TF-IDF used by BOTH keyword scorers (de-dup).

    ``decode_lc(i) -> str`` returns the LOWERED text of document ``i`` (decoded on
    demand so no full ``texts`` list is materialized -- the Phase 2b peak-memory
    fix). Runs the two passes (corpus document-frequency accumulation, then the
    per-doc ``tf * idf`` base score) and returns the base TF-IDF score per doc
    index. Callers layer their OWN boosts (bigram/trigram, technical-term,
    recency) and any refinement stage on top -- those stay out of this helper.

    Semantics are byte-for-byte identical to the math previously inlined in each
    scorer (and to the old ``_compute_tfidf_scores``): same df pass, same
    ``lc.count(term)`` TF, same ``log(num_docs/df[term])`` IDF, and the empty-
    ``terms`` case yields ``1.0`` per doc.
    """
    # Corpus document-frequency pass.
    df = {}
    if terms:
        for term in terms:
            df[term] = 0
        for i in range(num_docs):
            lc = decode_lc(i)
            for term in terms:
                if term in lc:
                    df[term] += 1

    # Per-doc base TF-IDF pass.
    scores = []
    for i in range(num_docs):
        if not terms:
            scores.append(1.0)
            continue
        lc = decode_lc(i)
        score = 0.0
        for term in terms:
            tf = lc.count(term)
            if tf > 0 and df[term] > 0:
                idf = math.log(num_docs / df[term])
                score += tf * idf
        scores.append(score)
    return scores

def _keyword_retrieve_scored(vol_txt: str, query: str, k: int = 3) -> List[Tuple[str, str]]:
    """Core enhanced keyword retrieval (TF-IDF + n-gram boosts).

    Returns ranked ``(snap_id, text)`` tuples so callers can choose ids or text
    without re-running the scorer. The snap_id is extracted directly from each
    snapshot block's START marker (canonical id, no text-equality reverse-map).
    """
    terms = _extract_terms(query)
    bigrams = _generate_ngrams(query, 2)
    trigrams = _generate_ngrams(query, 3)

    if not terms and not bigrams and not trigrams:
        return []

    # PHASE 2b PEAK FIX: keep only the (start, end) char offsets into vol_txt, NOT a
    # materialized list of ~7176 decoded snapshot substrings (~89 MB of str objects).
    # Each snapshot is sliced from vol_txt on demand -- twice (corpus df pass, then
    # scoring pass) -- holding only one lowered substring at a time, and the top-k
    # substrings are sliced for the return value. This is byte-for-byte identical to
    # the old _compute_tfidf_scores + scoring loop (same df pass, same `lc.count`,
    # same `log(num_docs/df)` IDF, same bigram/trigram boosts, same `score > 0`
    # filter, same iteration/sort order) -- it only changes WHERE/WHEN text is held.
    spans = split_snapshot_spans(vol_txt)
    num_docs = len(spans)

    def _decode_lc(i):
        s, e = spans[i]
        return vol_txt[s:e].lower()

    # Shared streaming base TF-IDF (df pass + per-doc tf*idf); boosts added below.
    base = _streaming_tfidf_scores(_decode_lc, num_docs, terms)

    scored = []
    for i, (s, e) in enumerate(spans):
        lc = vol_txt[s:e].lower()
        score = base[i]

        # Boost for exact phrase matches (n-grams)
        for bigram in bigrams:
            if bigram in lc:
                score += 5.0  # Significant boost for 2-word phrase match

        for trigram in trigrams:
            if trigram in lc:
                score += 10.0  # Even larger boost for 3-word phrase match

        if score > 0:
            scored.append((score, i))

    scored.sort(key=lambda x: x[0], reverse=True)
    out = []
    for _, i in scored[:k]:
        s, e = spans[i]
        text = vol_txt[s:e]
        # Extract canonical snap_id from this block's START marker.
        sid_m = START_RX.search(text)
        sid = sid_m.group("snap") if sid_m else ""
        out.append((sid, text))
    return out


def keyword_retrieve(vol_txt: str, query: str, k: int = 3) -> List[str]:
    """Enhanced keyword retrieval with stop-word filtering, TF-IDF, and n-gram matching.

    Thin wrapper over :func:`_keyword_retrieve_scored` (returns snapshot texts).
    """
    return [text for _sid, text in _keyword_retrieve_scored(vol_txt, query, k)]


def keyword_retrieve_ids(vol_txt: str, query: str, k: int = 3) -> List[str]:
    """Same ranking as :func:`keyword_retrieve` but returns snap_ids.

    Lets the hybrid fuser combine keyword + semantic results by snap_id without
    rebuilding the full snap_to_text map or doing an O(n^2) text-equality remap.
    """
    return [sid for sid, _text in _keyword_retrieve_scored(vol_txt, query, k)]

def _keyword_retrieve_for_operator_scored(vol_txt: str, query: str, k: int, op: str) -> List[Tuple[str, str]]:
    """Core operator-aware keyword retrieval. Uses index for O(1) operator filtering.

    Returns ranked ``(snap_id, text)`` tuples (carries the canonical snap_id
    through both the index-scoring stage and the re-scoring refinement stage so
    the hybrid fuser can combine by id without a text-equality reverse-map).

    Special case: "system" operator can see ALL snapshots from all operators.
    """
    index = load_snapshot_index()

    if index:
        # Use index to pre-filter by operator - "system" sees all
        if op == "system":
            matching = [(snap_id, meta) for snap_id, meta in index.items()]
        else:
            matching = [(snap_id, meta) for snap_id, meta in index.items() if meta.get("operator") == op]
        matching.sort(key=lambda x: x[0])
        recent = matching[:]  # Get all snapshots (no limit)

        # FIX 1: Read as BYTES to use byte offsets correctly (not string slicing)
        vol_bytes = read_volume_bytes(VOL_PATH)
        vol_len = len(vol_bytes)

        # snap_ids are known from the index entries; keep just the id list.
        sids = [snap_id for snap_id, _meta in recent]

        # Now run keyword matching on pre-filtered snapshots
        terms = _extract_terms(query)
        bigrams = _generate_ngrams(query, 2)
        trigrams = _generate_ngrams(query, 3)

        if not terms and not bigrams and not trigrams:
            return []

        # PHASE 2b PEAK FIX: do NOT materialize the full decoded `texts` list.
        # Holding `vol_bytes` (~37 MB) alongside a decoded-string copy of the WHOLE
        # corpus (~89 MB of str objects) was the per-call high-water mark (~127 MB).
        # Instead we decode each snapshot on demand (twice -- once for the corpus
        # document-frequency pass, once for scoring) and keep only the lowered text
        # for ONE snapshot at a time, then decode the top-k for the return value.
        # This is byte-for-byte identical to the old _compute_tfidf_scores + scoring
        # loop (same df pass, same `lc.count(term)` TF, same `log(num_docs/df)` IDF,
        # same technical/recency/bigram/trigram boosts, same `score > 0` filter, same
        # iteration/sort order) -- verified bit-equal -- it only changes WHERE/WHEN
        # text is held. The cost is a second decode pass (CPU), trading it for memory.
        num_texts = len(recent)

        def _decode_lc(i):
            meta = recent[i][1]
            start = meta["byte_start"]
            end = meta["byte_end"]
            if start < vol_len and end <= vol_len:
                return vol_bytes[start:end].decode('utf-8', errors='replace').lower()
            return ""

        # Shared streaming base TF-IDF (df pass + per-doc tf*idf); boosts added below.
        base = _streaming_tfidf_scores(_decode_lc, num_texts, terms)

        technical_term_count = sum(1 for term in terms if term in TECHNICAL_TERMS)
        scored = []
        for i in range(num_texts):
            lc = _decode_lc(i)
            score = base[i]

            # Add technical term boost: if query contains technical terms, boost score
            if technical_term_count > 0:
                # Check if this snapshot contains those technical terms
                matched_technical = sum(1 for term in terms if term in TECHNICAL_TERMS and term in lc)
                if matched_technical > 0:
                    technical_boost = (matched_technical / technical_term_count) * 3.0  # Up to +3.0
                    score += technical_boost

            # FIX 2: Add recency bonus - newer snapshots rank higher
            # i=0 is oldest in recent[] list, i=num_texts-1 is newest
            if num_texts > 1:
                recency_factor = i / (num_texts - 1)  # 0.0 to 1.0
                recency_bonus = recency_factor * 2.0  # Up to +2.0 for most recent
                score += recency_bonus

            for bigram in bigrams:
                if bigram in lc:
                    score += 5.0

            for trigram in trigrams:
                if trigram in lc:
                    score += 10.0

            if score > 0:
                # Hold only the INDEX i (not the decoded text).
                scored.append((score, i))

        scored.sort(key=lambda x: x[0], reverse=True)
        # Decode text for the top-k only (from vol_bytes byte offsets).
        base = []
        for _, i in scored[:k]:
            meta = recent[i][1]
            start = meta["byte_start"]
            end = meta["byte_end"]
            if start < vol_len and end <= vol_len:
                t = vol_bytes[start:end].decode('utf-8', errors='replace')
            else:
                t = ""
            base.append((sids[i], t))
    else:
        # Fallback to old method if index not available
        base_texts = keyword_retrieve(vol_txt, query, k=999999) if query else []  # Get all results (no limit)
        base_texts = filter_by_operator(base_texts, op)
        # Recover the canonical snap_id from each block's START marker.
        base = []
        for t in base_texts:
            m = START_RX.search(t)
            base.append((m.group("snap") if m else "", t))

    # Re-score after operator filtering (optional refinement)
    terms = _extract_terms(query)
    bigrams = _generate_ngrams(query, 2)
    trigrams = _generate_ngrams(query, 3)

    scored = []
    for sid, t in base:
        lc = t.lower()
        score = sum(lc.count(w) for w in terms) if terms else 1

        # Boost for phrases
        for bigram in bigrams:
            if bigram in lc:
                score += 5.0
        for trigram in trigrams:
            if trigram in lc:
                score += 10.0

        if score > 0:
            scored.append((score, sid, t))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [(sid, t) for _, sid, t in scored[:k]]


def keyword_retrieve_for_operator(vol_txt: str, query: str, k: int, op: str) -> List[str]:
    """Operator-aware wrapper for enhanced keyword retrieval (returns texts).

    Thin wrapper over :func:`_keyword_retrieve_for_operator_scored`.
    """
    return [text for _sid, text in _keyword_retrieve_for_operator_scored(vol_txt, query, k, op)]


def keyword_retrieve_ids_for_operator(vol_txt: str, query: str, k: int, op: str) -> List[str]:
    """Same ranking as :func:`keyword_retrieve_for_operator` but returns snap_ids."""
    return [sid for sid, _text in _keyword_retrieve_for_operator_scored(vol_txt, query, k, op)]

# -----------------------------------------------------------------------------
# Checkpoint System (Per-Operator Memory Compression)
# -----------------------------------------------------------------------------
def get_latest_checkpoint_for_operator(vol_txt: str, op: str) -> Optional[str]:
    """Retrieve the most recent checkpoint snapshot for an operator.

    Checkpoints are special snapshots with type="checkpoint" that contain
    compressed summaries of the last 50 conversation turns.
    """
    index = load_snapshot_index()

    if not index:
        # Fallback: parse volume text to find checkpoints
        blocks = split_snapshots(vol_txt)
        checkpoints = []
        for snap_id, start, end in blocks:
            meta_match = re.search(r'OPERATOR:\s*(\S+)', vol_txt[start:end])
            type_match = re.search(r'TYPE:\s*(\S+)', vol_txt[start:end])

            if meta_match and type_match:
                snap_op = meta_match.group(1)
                snap_type = type_match.group(1)
                if snap_op == op and snap_type == "checkpoint":
                    checkpoints.append((snap_id, vol_txt[start:end]))

        if checkpoints:
            # Return the most recent checkpoint
            checkpoints.sort(key=lambda x: x[0])
            return checkpoints[-1][1]
        return None

    # Use index for fast retrieval
    matching = [
        (snap_id, meta)
        for snap_id, meta in index.items()
        if meta.get("operator") == op and meta.get("type") == "checkpoint"
    ]

    if not matching:
        return None

    # Sort by snap_id and get most recent
    matching.sort(key=lambda x: x[0])
    snap_id, meta = matching[-1]

    # Read the checkpoint snapshot
    vol_bytes = read_volume_bytes(VOL_PATH)
    byte_start = meta.get("byte_start", 0)
    byte_end = meta.get("byte_end", len(vol_bytes))

    try:
        snapshot_bytes = vol_bytes[byte_start:byte_end]
        return snapshot_bytes.decode('utf-8', errors='replace')
    except Exception as e:
        print(f"[CHECKPOINT] Error reading checkpoint {snap_id}: {e}")
        return None


def get_recent_checkpoints_for_operator(vol_txt: str, op: str, count: int = 1) -> list[str]:
    """Retrieve the N most recent checkpoint snapshots for an operator.

    Args:
        vol_txt: Volume text content
        op: Operator name
        count: Number of checkpoints to retrieve (default: 1)

    Returns:
        List of checkpoint snapshot texts, ordered from oldest to newest
    """
    if count <= 0:
        return []

    index = load_snapshot_index()

    if not index:
        # Fallback: parse volume text to find checkpoints
        blocks = split_snapshots(vol_txt)
        checkpoints = []
        for snap_id, start, end in blocks:
            meta_match = re.search(r'OPERATOR:\s*(\S+)', vol_txt[start:end])
            type_match = re.search(r'TYPE:\s*(\S+)', vol_txt[start:end])

            if meta_match and type_match:
                snap_op = meta_match.group(1)
                snap_type = type_match.group(1)
                if snap_op == op and snap_type == "checkpoint":
                    checkpoints.append((snap_id, vol_txt[start:end]))

        if checkpoints:
            # Sort by snap_id and return N most recent
            checkpoints.sort(key=lambda x: x[0])
            return [snap for _, snap in checkpoints[-count:]]
        return []

    # Use index for fast retrieval
    matching = [
        (snap_id, meta)
        for snap_id, meta in index.items()
        if meta.get("operator") == op and meta.get("type") == "checkpoint"
    ]

    if not matching:
        return []

    # Sort by snap_id and get N most recent
    matching.sort(key=lambda x: x[0])
    recent_matches = matching[-count:]

    # Read the checkpoint snapshots
    vol_bytes = read_volume_bytes(VOL_PATH)
    checkpoints = []

    for snap_id, meta in recent_matches:
        byte_start = meta.get("byte_start", 0)
        byte_end = meta.get("byte_end", len(vol_bytes))

        try:
            snapshot_bytes = vol_bytes[byte_start:byte_end]
            checkpoint_text = snapshot_bytes.decode('utf-8', errors='replace')
            checkpoints.append(checkpoint_text)
        except Exception as e:
            print(f"[CHECKPOINT] Error reading checkpoint {snap_id}: {e}")

    return checkpoints
