#!/usr/bin/env python3
from __future__ import annotations

"""
startup.py - Extracted from Orchestrator/app.py

This module was automatically extracted using byte-offset manifest refactoring.
Original location: Lines 3702-3845

Extraction date: 2025-12-10T22:40:50.457843+00:00
Original SHA-256: ef19b35b98d461528de8fae91c27887ef850830798abe8b12e25015e169ea471
"""

# Standard library imports
import logging
import os
from pathlib import Path
import re
import sys
import signal
import threading
from typing import Dict, Any, Optional, List

logger = logging.getLogger("blackbox.startup")

# External library imports
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

# Local imports - Import app from checkpoint to register event handlers
from Orchestrator.checkpoint import app
from Orchestrator.config import SNAPSHOT_INDEX, OPERATOR_STATE_FILE, APPS_REGISTRY_FILE, UPLOADS_DIR, VOL_PATH, START_RX
from Orchestrator.fossils import (
    load_snapshot_index, rebuild_snapshot_index, update_snapshot_index,
    read_schema_version, write_schema_version, CURRENT_SCHEMA_VERSION,
)
from Orchestrator.volume import cleanup_old_archives, read_text_safe, read_volume_bytes, cleanup_old_artifacts
from Orchestrator.state import load_operator_state, load_operator_preferences, load_app_registry

# Additional imports (auto-generated by dependency audit)
from Orchestrator.monitoring import cleanup_stuck_tasks, get_disk_usage
from Orchestrator.scheduler import get_scheduler_manager


def shutdown_handler(signum, frame):
    """Handle SIGTERM/SIGINT for graceful shutdown"""
    logger.info("Received signal %s, shutting down gracefully...", signum)
    logger.info("Stopping background worker...")
    # The worker thread is daemon=True, so it will stop when main thread exits
    logger.info("Shutdown complete")
    sys.exit(0)

# Register signal handlers
signal.signal(signal.SIGTERM, shutdown_handler)  # systemd stop
signal.signal(signal.SIGINT, shutdown_handler)   # Ctrl+C

def _incremental_index_update(index, vol_bytes, scan_from_byte):
    """Process only new snapshots from a byte offset instead of full rebuild.

    Scans the volume from `scan_from_byte` forward, indexing any new snapshots
    found in the tail. Instant for typical restarts where only a few snapshots
    were minted since the last clean index.
    """
    import time
    from Orchestrator.fossils import save_snapshot_index
    start_time = time.time()

    tail = vol_bytes[scan_from_byte:]
    START_RX_B = re.compile(rb'=== START SNAPSHOT \xe2\x80\x94 UTC (?P<utc>\d{4}-\d{2}-\d{2}T[\d:]+Z) \xe2\x80\x94 (?P<snap>SNAP-\d{8}-\d+)')
    OP_RX_B = re.compile(rb'OPERATOR:\s*([^\n]+)')

    added = 0
    for m_start in START_RX_B.finditer(tail):
        snap_id = m_start.group("snap").decode('utf-8')
        if snap_id in index:
            continue

        utc = m_start.group("utc").decode('utf-8')

        end_pattern = rb'=== END SNAPSHOT \xe2\x80\x94 ' + re.escape(snap_id.encode()) + rb'.*?==='
        m_end = re.search(end_pattern, tail[m_start.end():m_start.end() + 200000])
        if not m_end:
            continue

        byte_start = scan_from_byte + m_start.start()
        byte_end = scan_from_byte + m_start.end() + m_end.end()

        snap_bytes = vol_bytes[byte_start:byte_end]
        operator = "Unknown"
        op_match = OP_RX_B.search(snap_bytes)
        if op_match:
            operator = op_match.group(1).strip().decode('utf-8', errors='replace')

        snap_type = "checkpoint" if b"[CHECKPOINT]" in snap_bytes else "normal"

        index[snap_id] = {
            "byte_start": byte_start,
            "byte_end": byte_end,
            "operator": operator,
            "timestamp": utc,
            "type": snap_type
        }
        added += 1

    save_snapshot_index(index)
    elapsed = time.time() - start_time
    logger.info("Incremental update: added %d snapshots in %.2fs (total: %d)", added, elapsed, len(index))


# Startup: Initialize or rebuild snapshot index
@app.on_event("startup")
def startup_check_index():
    """Check if snapshot index exists, rebuild if missing or stale. Also run cleanup."""
    logger.info("Checking snapshot index...")

    if not SNAPSHOT_INDEX.exists():
        logger.info("Index not found, rebuilding...")
        rebuild_snapshot_index()
    elif read_schema_version() != CURRENT_SCHEMA_VERSION:
        # T1 / audit M9: schema sentinel mismatch (or pre-versioning install).
        # Rebuild from volume — the canonical source of truth — so the on-disk
        # index matches what current code expects to parse.
        on_disk = read_schema_version()
        logger.warning(
            "Snapshot index schema version mismatch (on-disk=%d, code=%d). "
            "Rebuilding index from volume...",
            on_disk, CURRENT_SCHEMA_VERSION,
        )
        rebuild_snapshot_index()
    else:
        try:
            index = load_snapshot_index()
            index_count = len(index)

            if not VOL_PATH.exists():
                logger.info("No volume file found, index is empty")
            else:
                vol_size = VOL_PATH.stat().st_size
                # Check if volume has grown since last indexed snapshot
                max_byte_end = max((v.get("byte_end", 0) for v in index.values()), default=0)

                if vol_size == max_byte_end:
                    logger.info("Index is current with %d snapshots (volume unchanged)", index_count)
                elif vol_size > max_byte_end:
                    new_bytes = vol_size - max_byte_end
                    if new_bytes < 100:
                        # Trailing whitespace/newline — not a real snapshot
                        logger.info("Index is current with %d snapshots (volume has %d trailing bytes)", index_count, new_bytes)
                    else:
                        # Volume has new data — incrementally index only the new tail
                        logger.info("Volume grew by %d bytes since last index, running incremental update...", new_bytes)
                        vol_bytes = read_volume_bytes(VOL_PATH)
                        _incremental_index_update(index, vol_bytes, max_byte_end)
                else:
                    # Volume shrunk or something weird — full rebuild
                    logger.info("Volume size mismatch (indexed up to byte %d, volume is %d bytes), rebuilding...", max_byte_end, vol_size)
                    rebuild_snapshot_index()
        except Exception as e:
            logger.error("Error checking index: %s, rebuilding...", e)
            rebuild_snapshot_index()

    # Load operator state after index is ready
    load_operator_state()

    # Load operator preferences (cross-device sync)
    load_operator_preferences()

    # Load registered apps from disk
    load_app_registry()

    # Run artifact cleanup on startup (4-day retention)
    logger.info("Running artifact cleanup...")
    cleanup_old_artifacts()

    # Run archive cleanup on startup
    logger.info("Running archive cleanup...")
    try:
        cleanup_stats = cleanup_old_archives(days_to_keep=30, max_size_gb=5.0, max_files=200)
        if cleanup_stats["deleted_files"] > 0:
            logger.info("Cleaned up %d archives (%.1f MB freed)",
                        cleanup_stats["deleted_files"], cleanup_stats["deleted_size_mb"])
        logger.info("Archive status: %d files, %.1f MB total",
                    cleanup_stats["remaining_files"], cleanup_stats["remaining_size_mb"])

        # Check disk space
        disk_usage = get_disk_usage()
        if disk_usage["warnings"]:
            for warning in disk_usage["warnings"]:
                logger.warning("%s", warning)
        logger.info("Disk usage: %.1f%%, %.1f GB free",
                    disk_usage["disk"]["percent"], disk_usage["disk"]["free_gb"])

        # Clean up stuck tasks
        logger.info("Checking for stuck tasks...")
        task_cleanup_stats = cleanup_stuck_tasks(max_hours=24)
        if task_cleanup_stats["marked_failed"] > 0:
            logger.info("Marked %d stuck tasks as failed", task_cleanup_stats["marked_failed"])
            for task in task_cleanup_stats["failed_tasks"]:
                hours = task["hours_stuck"]
                hours_str = f"{hours:.1f}" if isinstance(hours, (int, float)) else str(hours)
                logger.info("  - %s task stuck for %s hours", task["task_type"], hours_str)
        else:
            logger.info("No stuck tasks found (%d tasks checked)", task_cleanup_stats["checked"])
    except Exception as e:
        logger.error("Error during cleanup: %s", e)

    # Sovereign Browser displays are per-session (M9): allocated on demand at each
    # CU launch, not a single global display. At boot, reap any restart-survivor
    # Xvfb/x11vnc/websockify children left on our slot displays/ports by a previous
    # process (KillMode=process reparents them to init) so their slots are reusable.
    logger.info("Reaping orphaned Sovereign Browser display children...")
    try:
        from Orchestrator.browser.display import get_allocator
        get_allocator().reap_orphans()
        logger.info("Sovereign Browser per-session displays ready (allocated on demand)")
    except Exception as e:
        logger.error("Sovereign Browser display boot-reap error: %s", e)

    # Start background worker thread for task processing (lazy import to avoid circular import)
    logger.info("Starting background worker thread...")
    from Orchestrator.tasks import background_worker
    worker_thread = threading.Thread(target=background_worker, daemon=True)
    worker_thread.start()
    logger.info("Background worker thread started")



@app.on_event("startup")
def startup_embeddings_transcode():
    """One-time migration: inline index embeddings → binary vector store.

    Registered immediately AFTER startup_check_index so the snapshot index
    has been created/rebuilt/healed before we slim it (FastAPI runs startup
    hooks in registration order). Runs synchronously ON PURPOSE: no request
    is served until startup hooks return, so nothing can mint a snapshot
    (rewriting the index) while transcode holds the full index in memory —
    a background thread here could clobber a freshly minted entry. The cost
    is one ~408MB JSON parse on merge-day boot; every later boot hits the
    slim-index no-op path instantly.

    NEVER raises — a transcode failure must not block boot. NOTE: there is
    no inline-vector fallback (removed in Task 16); until a rerun succeeds,
    semantic search returns no results and keyword search carries the load.
    """
    try:
        from Orchestrator.embeddings.transcode import transcode_inline_embeddings
        result = transcode_inline_embeddings()
        if result.get("skipped"):
            logger.info(
                "[TRANSCODE] skipped: %s",
                result.get("reason", "no inline embeddings in index"),
            )
        else:
            logger.info(
                "[TRANSCODE] migrated=%d dropped=%d index %d->%d bytes",
                result["migrated"], result["dropped"],
                result["index_bytes_before"], result["index_bytes_after"],
            )
    except Exception as e:  # noqa: BLE001 — must never crash startup.
        logger.error(
            "[TRANSCODE] startup transcode failed (non-fatal, index left "
            "untouched): %s", e,
        )


@app.on_event("startup")
async def startup_embeddings_migration_resume():
    """Relaunch an embeddings migration that a restart interrupted (Task 8).

    migration_state.json saying state=="running" means the process died
    mid-job. The job is resumable by construction (progress truth = the
    target store's contents; the engine re-diffs), so we just schedule
    run_migration(target) as a background task. Async hook ON PURPOSE:
    resume_if_interrupted() needs the running event loop to create_task —
    the job must outlive startup, not block it.

    NEVER raises — a resume failure must not block boot (the operator can
    re-POST /embeddings/migrate; the stores are untouched).
    """
    try:
        from Orchestrator.embeddings.migrate import resume_if_interrupted
        task = resume_if_interrupted()
        if task is not None:
            logger.info("[MIGRATE] resumed interrupted embeddings migration")
    except Exception as e:  # noqa: BLE001 — must never crash startup.
        logger.error("[MIGRATE] startup resume check failed (non-fatal): %s", e)


@app.on_event("startup")
async def startup_embeddings_watcher():
    """Schedule the daily embedding-model deprecation watcher (Task 9).

    A plain asyncio loop task on the app's event loop: first health check
    runs ~5 minutes after boot (startup is already index-rebuild heavy),
    then daily. Registered AFTER the migration-resume hook so a resumed
    job claims the migration singleton before any watcher-initiated
    auto-migrate could race it.

    NEVER raises — the watcher is maintenance, not boot criteria;
    POST /embeddings/health/check is the manual fallback.
    """
    try:
        from Orchestrator.embeddings.watcher import start_watcher
        start_watcher()
        logger.info("[WATCHER] embeddings deprecation watcher scheduled (daily)")
    except Exception as e:  # noqa: BLE001 — must never crash startup.
        logger.error("[WATCHER] failed to schedule watcher (non-fatal): %s", e)


@app.on_event("startup")
async def startup_notify_bridge():
    """Capture the main event loop for the sync→async notify() bridge (MN.7).

    The highest-volume notification producer (tasks.py:update_task) runs in a
    sync worker thread with no loop of its own. It schedules notify() onto THIS
    loop via asyncio.run_coroutine_threadsafe — the same pattern the scheduler
    uses. We must capture the loop from inside a running-loop coroutine, so this
    is an async startup hook.

    NEVER raises — a capture failure only means producers fall back to a logged
    no-op (their own work is unaffected), so it must not block boot.
    """
    try:
        from Orchestrator.notifications.bridge import set_main_loop
        set_main_loop()
        logger.info("[NOTIFY-BRIDGE] main event loop captured for background notify()")
    except Exception as e:  # noqa: BLE001 — must never crash startup.
        logger.error("[NOTIFY-BRIDGE] failed to capture main loop (non-fatal): %s", e)


@app.on_event("startup")
async def startup_live_session_reaper():
    """Start the live voice-session reaper (memory-leak fix 2026-06-14).

    GEMINI_LIVE_SESSIONS / GROK_LIVE_SESSIONS / REALTIME_SESSIONS were append-only
    and grew RAM unbounded (dead sessions retained their transcript + base64 audio).
    The reaper periodically evicts sessions marked status="disconnected" past a short
    reconnect grace window. A plain asyncio loop on the app event loop; the route
    disconnect handlers already release the heavy audio buffers immediately.

    NEVER raises — maintenance, not boot criteria.
    """
    try:
        from Orchestrator.live_session_reaper import start_reaper
        start_reaper()
        logger.info("[LIVE-REAPER] live voice-session reaper started (sweep 60s)")
    except Exception as e:  # noqa: BLE001 — must never crash startup.
        logger.error("[LIVE-REAPER] failed to start reaper (non-fatal): %s", e)


@app.on_event("startup")
def startup_assert_sudoers_current():
    """Auto-update /etc/sudoers.d/blackbox-system if the template in this
    git checkout adds grants that aren't already present. Uses the
    `blackbox-write-systemd sudoers-system` helper (NOPASSWD-granted by
    the EXISTING sudoers file, so no password needed) which runs
    `visudo -c` before installing.

    Why this exists (Brandon 2026-05-24): the update pipeline's
    systemd_regen phase tries `sudo -n bash install.sh`. The original
    sudoers file didn't grant that, so the call would fail with a
    scary 'password required' message. cecc3c1 made the runner tolerate
    the failure but the message still alarmed customers. Adding the
    grant to the template fixes new installs; this startup hook ports
    the grant to EXISTING installs without requiring them to manually
    re-run install.sh.

    Idempotent: rendered template is compared byte-for-byte against the
    deployed file; helper only invoked when they differ. Failure is
    non-fatal — the worst case is the customer's old sudoers stays in
    place (same as today).
    """
    import subprocess
    import tempfile

    root = Path(__file__).resolve().parents[1]
    template = root / "installer" / "templates" / "sudoers-blackbox-system"
    deployed = "/etc/sudoers.d/blackbox-system"
    if not template.is_file():
        return
    real_user = os.environ.get("USER") or os.environ.get("LOGNAME") or "bbx"
    try:
        rendered = (
            template.read_text(encoding="utf-8")
            .replace("REAL_USER_PLACEHOLDER", real_user)
            .replace("BLACKBOX_ROOT_PLACEHOLDER", str(root))
        )
    except OSError as e:
        logger.warning("[sudoers] could not read template: %r", e)
        return
    # If the deployed file already matches, no action needed.
    try:
        with open(deployed, "r", encoding="utf-8", errors="replace") as f:
            current = f.read()
        if current == rendered:
            logger.info("[sudoers] /etc/sudoers.d/blackbox-system already current")
            return
    except (OSError, PermissionError):
        # File doesn't exist or we can't read it — fall through and try
        # to write (helper will fail gracefully if not permitted).
        pass

    helper = "/usr/local/sbin/blackbox-write-systemd"
    if not os.path.isfile(helper):
        logger.warning("[sudoers] helper %s missing; can't auto-update", helper)
        return

    try:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".sudoers",
                                          delete=False, encoding="utf-8") as tmp:
            tmp.write(rendered)
            tmp_path = tmp.name
        result = subprocess.run(
            ["sudo", "-n", helper, "sudoers-system", tmp_path],
            capture_output=True, text=True, timeout=10,
        )
        os.unlink(tmp_path)
        if result.returncode == 0:
            logger.info("[sudoers] auto-updated /etc/sudoers.d/blackbox-system "
                        "(new grants from template now active)")
        else:
            logger.warning("[sudoers] helper failed rc=%d stderr=%r",
                           result.returncode, result.stderr[:200])
    except (subprocess.TimeoutExpired, OSError) as e:
        logger.warning("[sudoers] auto-update errored: %r", e)


@app.on_event("startup")
def startup_assert_url_handlers():
    """Re-assert chromium-browser as the default URL handler for HTTP(S)
    and text/html every time the service starts. Brandon's MSO2 hit a
    persistent regression (2026-05-22 through 2026-05-23) where xdg-mime
    defaults drifted from chromium-browser to org.gnome.TextEditor.desktop
    between sessions — cause unknown (snap refresh? GNOME initial-setup?
    a user mis-click on a file association prompt?). install.sh Step 4i
    sets it once at install time but doesn't re-assert.

    Our PATH-shim xdg-open/gio interception in TmuxSessionManager covers
    CLIs that call those binaries directly. But CLIs that use D-Bus
    (org.freedesktop.portal.OpenURI) or GTK natively (gtk_show_uri)
    bypass PATH and consult xdg-mime defaults directly — Antigravity
    `agy` appears to do this since our shim invocation log stays empty
    when agy auto-opens its OAuth URL.

    Belt-and-suspenders: assert the default at startup. Idempotent
    (no-op if already correct). Failure here is non-fatal — the PATH
    shims are still in place as the secondary defense for CLIs that
    do use xdg-open/gio.
    """
    import os
    import shutil
    import subprocess
    # Pick the first browser .desktop file that actually exists on disk.
    candidates = [
        "chromium-browser.desktop",
        "chromium.desktop",
        "google-chrome.desktop",
        "firefox_firefox.desktop",   # snap
        "firefox.desktop",
    ]
    desktop_dirs = [
        "/usr/share/applications",
        "/var/lib/snapd/desktop/applications",
        os.path.expanduser("~/.local/share/applications"),
    ]
    chosen = None
    for desktop in candidates:
        for d in desktop_dirs:
            if os.path.isfile(os.path.join(d, desktop)):
                chosen = desktop
                break
        if chosen:
            break
    if not chosen:
        logger.warning("[url-handlers] no browser .desktop file found in %s — "
                       "URL-opening will fall through to xdg-mime defaults",
                       desktop_dirs)
        return
    # Need DBUS to talk to the user's GNOME session for xdg-mime to persist.
    uid = os.getuid()
    env = os.environ.copy()
    env.setdefault("DBUS_SESSION_BUS_ADDRESS", f"unix:path=/run/user/{uid}/bus")
    env.setdefault("XDG_RUNTIME_DIR", f"/run/user/{uid}")
    if shutil.which("xdg-mime") is None:
        logger.warning("[url-handlers] xdg-mime not on PATH; skipping default assertion")
        return
    schemes = [
        "text/html",
        "x-scheme-handler/http",
        "x-scheme-handler/https",
        "x-scheme-handler/about",
        "x-scheme-handler/unknown",
    ]
    try:
        result = subprocess.run(
            ["xdg-mime", "default", chosen, *schemes],
            env=env, capture_output=True, text=True, timeout=8,
        )
        if result.returncode == 0:
            logger.info("[url-handlers] asserted %s as default for %s",
                        chosen, ", ".join(schemes))
        else:
            logger.warning("[url-handlers] xdg-mime default failed rc=%d stderr=%r",
                           result.returncode, result.stderr[:200])
    except (subprocess.TimeoutExpired, OSError) as e:
        logger.warning("[url-handlers] xdg-mime invocation errored: %r", e)


@app.on_event("startup")
def startup_toolvault_embedding_sync():
    """Sync ToolVault embeddings against the canonical module list, once, at boot.

    Tool modules under ``ToolVault/tools/<name>/`` are the source of truth;
    ``embeddings.json`` is the only cache. On a fresh install (no embeddings.json)
    or after a module's description was edited, the affected tools must be
    (re-)embedded so semantic tool search keeps working. On a warm box (cache
    present, hashes match) this is a fast no-op.

    A cold install with all 48 tools to embed can take ~30s, so the work runs in
    a daemon thread to avoid blocking startup (FastAPI serves requests once the
    startup hooks return). A sync failure (e.g. no GOOGLE_API_KEY) is caught and
    logged as a warning — it must NEVER crash startup. Embeds that fail keep any
    prior cached vector intact (see embeddings.sync_embeddings).
    """
    def _run():
        try:
            from Orchestrator.toolvault import embeddings as tv_embeddings
            from Orchestrator.toolvault import registry as tv_registry

            canonical = tv_registry.load_canonical()
            store = tv_embeddings.sync_embeddings(canonical)
            # sync_embeddings prints its own embedded/skipped/pruned line; mirror
            # a concise summary into the startup logger for boot-log visibility.
            logger.info(
                "[TOOLVAULT] startup embedding sync complete: tools=%d cached=%d",
                len(canonical), len(store),
            )
        except Exception as e:  # noqa: BLE001 — must never crash startup.
            logger.warning(
                "[TOOLVAULT] startup embedding sync failed (non-fatal): %s", e,
            )

    logger.info("Starting ToolVault embedding sync (background)...")
    threading.Thread(
        target=_run, name="toolvault-embedding-sync", daemon=True
    ).start()


@app.on_event("startup")
async def startup_scheduler():
    """Start the cron job scheduler."""
    try:
        manager = get_scheduler_manager()
        await manager.start()
        logger.info("Cron scheduler started")
    except Exception as e:
        logger.error("Cron scheduler failed to start: %s", e)


@app.on_event("startup")
async def startup_cellular():
    """Initialize the cellular hotplug monitor (internet failover only).

    AT command telephony (modem, sms, voice) has been removed.
    Telephony now runs on Asterisk/PJSIP via the TG200 gateway.
    The hotplug monitor is retained for USB device detection.
    """
    from Orchestrator.config import CELLULAR_ENABLED
    if not CELLULAR_ENABLED:
        logger.info("Cellular module disabled (CELLULAR_ENABLED=false)")
        return

    try:
        from Orchestrator.cellular.hotplug import start_hotplug_monitor

        # Start hotplug monitor — detects USB modem plug/unplug for internet failover
        await start_hotplug_monitor()
        logger.info("Cellular hotplug monitor active (internet failover only)")
    except Exception as e:
        logger.error("Cellular hotplug monitor error: %s (non-fatal, continuing)", e)


@app.on_event("startup")
async def startup_cellular_internet():
    """Initialize the cellular internet failover manager."""
    from Orchestrator.config import CELLULAR_INTERNET_ENABLED
    if not CELLULAR_INTERNET_ENABLED:
        logger.info("Cellular internet manager disabled (CELLULAR_INTERNET_ENABLED=false)")
        return

    try:
        from Orchestrator.cellular.internet_manager import start_internet_manager
        mgr = await start_internet_manager()
        logger.info("Cellular internet manager active (connection=%s)", mgr._connection_name)
    except Exception as e:
        logger.error("Cellular internet manager error: %s (non-fatal, continuing)", e)


@app.on_event("startup")
async def startup_asterisk():
    """Initialize Asterisk ARI connection and AudioSocket server."""
    from Orchestrator.config import ASTERISK_ENABLED
    if not ASTERISK_ENABLED:
        logger.info("Asterisk integration disabled (ASTERISK_ENABLED=false)")
        return

    try:
        from Orchestrator.asterisk.audio_ipc import init_ipc_client
        from Orchestrator.asterisk.client import init_ari_client

        # Start audio subprocess (runs AudioSocket server in its own process)
        ipc_client = await init_ipc_client()
        if ipc_client:
            logger.info("Audio subprocess started (AudioSocket on port 9092)")
        else:
            logger.warning("Audio subprocess failed to start")

        # Connect to ARI
        ari_client = await init_ari_client()
        if ari_client and ari_client.is_connected:
            # Register inbound call handler
            from Orchestrator.routes.asterisk_routes import handle_inbound_call
            ari_client.on_stasis_start = handle_inbound_call
            logger.info("Asterisk ARI connected, inbound call handler registered")

            # Pre-generate IVR TTS prompts
            try:
                from Orchestrator.asterisk.ivr_audio import ensure_all_prompts
                await ensure_all_prompts()
                logger.info("IVR TTS prompts pre-generated")
            except Exception as e:
                logger.warning("IVR prompt generation failed: %s (non-fatal)", e)
        else:
            logger.warning("Asterisk ARI connection failed (will retry on demand)")

    except Exception as e:
        logger.error("Asterisk initialization error: %s (non-fatal, continuing)", e)


@app.on_event("startup")
async def startup_sms():
    """Initialize the SMS system (AMI client + router)."""
    from Orchestrator.config import ASTERISK_ENABLED
    if not ASTERISK_ENABLED:
        logger.info("SMS system disabled (ASTERISK_ENABLED=false)")
        return

    try:
        from Orchestrator.sms import start_sms_system
        await start_sms_system()
        logger.info("SMS system started (AMI connected, listening for inbound SMS)")
    except Exception as e:
        logger.error("SMS system startup error: %s (non-fatal, continuing)", e)


@app.on_event("startup")
async def startup_cli_agent_zellij():
    """Initialize the Zellij subsystem for the CLI Agent (Phase 2 T7).

    Wired BEFORE the first request is served (FastAPI startup events
    complete before request acceptance), satisfying audit C3's
    "reconcile MUST run before any route handler" constraint.

    Sequence (per Orchestrator/cli_agent/__init__.py):
      1. ensure_config()        — refresh ~/.config/zellij/config.kdl
      2. web_server_healthy()   — wait for zellij-web (up to ~10s)
      3. reconcile_or_wipe()    — state ↔ tokens.db consistency check

    NEVER raises — the orchestrator must boot even if Zellij is down.
    get_backend() returns "tmux" as the safe fallback in degraded mode.
    """
    try:
        import asyncio
        from Orchestrator.cli_agent import startup_initialize
        # ensure_config + web_server_healthy + reconcile are blocking
        # subprocess + filesystem + urllib work — punt to a worker thread
        # so we don't stall the event loop while other startup hooks run.
        await asyncio.to_thread(startup_initialize)
    except Exception as e:
        logger.error(
            "CLI Agent Zellij startup error: %s (non-fatal, continuing in "
            "tmux-only degraded mode)", e,
        )


@app.on_event("startup")
async def startup_cli_agent_zellij_reaper():
    """Start the periodic zellij idle-session reaper (Phase 2 housekeeping).

    The legacy reaper (Orchestrator/cli_agent/reaper.py reap_idle_sessions)
    is tmux-only and was never scheduled — so on a zellij box NOTHING reaped
    idle sessions, and ``(EXITED - attach to resurrect)`` zombies piled up
    (26-day-old sessions observed live 2026-06-22). This in-process task
    (mirroring live_session_reaper's pattern) sweeps hourly, deleting
    BlackBox-named zellij sessions older than the 7-day idle threshold
    (CLI_AGENT_IDLE_DAYS). Recently-used / resumed terminals keep a young
    "Created" age (attach resets it) and are never reaped.

    NEVER raises — maintenance, not boot criteria. Only starts when zellij
    is the effective backend.
    """
    try:
        from Orchestrator.cli_agent import get_backend
        if get_backend() != "zellij":
            logger.info(
                "[ZELLIJ-REAPER] backend is not zellij — reaper not started"
            )
            return
        from Orchestrator.cli_agent.reaper import (
            start_zellij_reaper, ZELLIJ_REAP_INTERVAL_SEC,
        )
        start_zellij_reaper()
        logger.info(
            "[ZELLIJ-REAPER] idle zellij-session reaper started (sweep %.0fs, "
            "7-day idle threshold)", ZELLIJ_REAP_INTERVAL_SEC,
        )
    except Exception as e:  # noqa: BLE001 — must never crash startup.
        logger.error("[ZELLIJ-REAPER] failed to start reaper (non-fatal): %s", e)


@app.on_event("shutdown")
async def shutdown_sms():
    """Stop the SMS system."""
    try:
        from Orchestrator.sms import stop_sms_system
        await stop_sms_system()
        logger.info("SMS system stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_asterisk():
    """Disconnect from Asterisk and stop AudioSocket server."""
    try:
        from Orchestrator.asterisk.client import get_ari_client
        client = get_ari_client()
        if client:
            await client.disconnect()
            logger.info("Asterisk ARI disconnected")
    except Exception:
        pass
    try:
        from Orchestrator.asterisk.audio_ipc import get_ipc_client
        client = get_ipc_client()
        if client:
            await client.shutdown()
            logger.info("Audio subprocess stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_cellular_internet():
    """Stop the cellular internet manager."""
    try:
        from Orchestrator.cellular.internet_manager import stop_internet_manager
        await stop_internet_manager()
        logger.info("Cellular internet manager stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_cellular():
    """Stop the cellular hotplug monitor."""
    try:
        from Orchestrator.cellular.hotplug import stop_hotplug_monitor
        await stop_hotplug_monitor()
        logger.info("Cellular hotplug monitor stopped")
    except Exception:
        pass


@app.on_event("shutdown")
async def shutdown_scheduler():
    """Stop the cron job scheduler."""
    try:
        manager = get_scheduler_manager()
        await manager.shutdown()
        logger.info("Cron scheduler stopped")
    except Exception:
        pass

from starlette.middleware.base import BaseHTTPMiddleware

class StaticCacheMiddleware(BaseHTTPMiddleware):
    """Add Cache-Control headers for static assets served from /ui/."""
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        path = request.url.path
        if path.startswith("/ui/"):
            if any(path.endswith(ext) for ext in ('.png', '.jpg', '.svg', '.woff2', '.ico')):
                # Binary media rarely changes — cache it.
                response.headers["Cache-Control"] = "public, max-age=3600, must-revalidate"
            elif (any(path.endswith(ext) for ext in ('.css', '.js'))
                  or path.endswith('.html') or path == "/ui/" or path == "/ui"):
                # JS/CSS/HTML must REVALIDATE every load. The ?v= bump on the entry
                # script does NOT bust relative ES-module deep imports (e.g.
                # stt-stream.js imported by tts-stt.js), so max-age caching served
                # stale modules for up to an hour and required manual cache clears.
                # "no-cache" + the StaticFiles etag = a cheap 304 when unchanged,
                # a fresh fetch the moment a module changes. (Caught 2026-06-05.)
                response.headers["Cache-Control"] = "no-cache"
        return response

app.add_middleware(StaticCacheMiddleware)

app.mount("/ui", StaticFiles(directory="Portal", html=True), name="ui")

class ChatIn(BaseModel):
    messages: Optional[list] = None 
    operator: Optional[str] = None
    provider: Optional[str] = None
    model: Optional[str] = None
    
class ImageData(BaseModel):
    data: str  # Base64 encoded image
    mime_type: str

class ReferenceImage(BaseModel):
    """Reference image for Nano Banana Pro style/subject guidance"""
    data: str  # Base64 encoded image data (without data:image/xxx;base64, prefix)
    mimeType: str  # image/jpeg, image/png, image/webp, image/gif

class GenIn(BaseModel):
    prompt: str
    operator: Optional[str] = None
    # Video generation options (Veo 3.1)
    aspectRatio: Optional[str] = "16:9"  # Also used for image generation
    resolution: Optional[str] = "720p"  # For video; images use 1K, 2K, 4K
    duration: Optional[int] = 8  # Duration in seconds (4, 6, or 8)
    durationSeconds: Optional[str] = None  # Legacy - use 'duration' instead
    negativePrompt: Optional[str] = None  # Things to exclude from video
    image: Optional[ImageData] = None  # For image-to-video (base64 data)
    image_url: Optional[str] = None  # For image-to-video (URL like /ui/uploads/image.png)
    # Image generation options (Nano Banana Pro / Gemini Imagen)
    numberOfImages: Optional[int] = 1  # 1-4 images at a time
    referenceImages: Optional[List[ReferenceImage]] = None  # Up to 14 reference images for style guidance
    provider: Optional[str] = None  # Image provider: "gemini" (default), "openai", "grok"
    size: Optional[str] = None  # OpenAI gpt-image size: 1024x1024 / 1536x1024 / 1024x1536 / auto
    quality: Optional[str] = None  # OpenAI gpt-image quality: low / medium / high

class AudioAnalysisIn(BaseModel):
    file_path: str
    operator: Optional[str] = None
    prompt: Optional[str] = "Generate a transcript with timestamps, identify speakers, and analyze emotions in this audio."

class VideoExtensionIn(BaseModel):
    video_url: str
    prompt: Optional[str] = ""
    operator: Optional[str] = None


# --- NEW: Google SSML Generation ---
class GoogleSSMLIn(BaseModel):
    text: Optional[str] = None
    ssml: Optional[str] = None
    voice_name: str
    speaking_rate: float = 1.0
    pitch: float = 0.0
    operator: Optional[str] = None # Added operator

# --- NEW: Gemini Pro TTS Generation ---
class GeminiProTTSIn(BaseModel):
    text: str
    voice_name: Optional[str] = "Charon"  # Default for single-speaker mode
    operator: Optional[str] = None
    multi_speaker: Optional[bool] = False  # Enable multi-speaker mode
    speakers: Optional[List[Dict[str, str]]] = None  # List of {name, voice} dicts for multi-speaker
    model: Optional[str] = "gemini-2.5-pro-tts"  # Model: gemini-2.5-pro-tts or gemini-2.5-flash-tts

# --- NEW: Lyria-002 Music Generation ---
class LyriaMusicIn(BaseModel):
    prompt: str  # e.g. "Epic orchestral movie trailer music with thundering drums"
    negative_prompt: Optional[str] = None  # e.g. "vocals, singing, speech"
    seed: Optional[int] = None  # For reproducible generation (mutually exclusive with sample_count > 1)
    sample_count: Optional[int] = 1  # Number of variations to generate (1-4, cannot use with seed)
    operator: Optional[str] = None

