#!/usr/bin/env python3
from __future__ import annotations

"""
tts_routes.py - OpenAI TTS, Google TTS, Gemini TTS, Lyria music
"""

# Standard library imports
import asyncio
import io
import json
import os
import base64
import re
import struct
import time
import uuid
import wave
from concurrent.futures import ThreadPoolExecutor
from typing import Dict, Any, Optional, List

# HTTP client
import requests

# Google Auth
from google.oauth2 import service_account
from google.auth.transport.requests import Request as GoogleAuthRequest

# External library imports
from fastapi import HTTPException, WebSocket, Body, UploadFile, File, Form
from fastapi.responses import StreamingResponse

# Local imports
from Orchestrator.checkpoint import app
from Orchestrator.startup import GoogleSSMLIn, GeminiProTTSIn, LyriaMusicIn, GenIn, VideoExtensionIn

# Additional imports (auto-generated by dependency audit)
from Orchestrator.config import AUDIO_ENGINE, CLOUD_TTS_URL, GEMINI_BASE_URL, GOOGLE_API_KEY, GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_AUTH_AVAILABLE, GOOGLE_TTS_SYNTHESIZE_URL, GOOGLE_TTS_VOICES_URL, LYRIA_MUSIC_URL, OPENAI_API_KEY, OPENAI_TTS_URL, TTS_FORMAT, TTS_MODEL, TTS_TIMEOUT, TTS_VOICE, UPLOADS_DIR, USE_CLOUD_TTS, VOL_PATH
from Orchestrator.fossils import load_snapshot_index
from Orchestrator.tts_sanitize import sanitize_for_speech
from Orchestrator.models import TaskType
from Orchestrator.state import get_operator_preference, save_operator_preferences, set_operator_preference, OPERATOR_PREFERENCES
from Orchestrator.tasks import create_task


@app.get("/operator/preferences/{operator}")
def get_preferences(operator: str):
    """Get all preferences for an operator (voice, model, etc.)"""
    prefs = OPERATOR_PREFERENCES.get(operator, {})
    return {"status": "ok", "operator": operator, "preferences": prefs}


@app.post("/operator/preferences/{operator}")
def set_preferences(operator: str, body: dict = Body(...)):
    """Set preferences for an operator. Body should contain key-value pairs."""
    try:
        if operator not in OPERATOR_PREFERENCES:
            OPERATOR_PREFERENCES[operator] = {}

        # Merge new preferences
        for key, value in body.items():
            OPERATOR_PREFERENCES[operator][key] = value

        save_operator_preferences()
        return {
            "status": "ok",
            "operator": operator,
            "preferences": OPERATOR_PREFERENCES[operator]
        }
    except Exception as e:
        return {"status": "error", "error": str(e)}


@app.get("/operator/preferences/{operator}/{key}")
def get_preference_key(operator: str, key: str):
    """Get a specific preference for an operator"""
    value = get_operator_preference(operator, key)
    return {"status": "ok", "operator": operator, "key": key, "value": value}


@app.put("/operator/preferences/{operator}/{key}")
def set_preference_key(operator: str, key: str, body: dict = Body(...)):
    """Set a specific preference for an operator"""
    value = body.get("value")
    set_operator_preference(operator, key, value)
    return {"status": "ok", "operator": operator, "key": key, "value": value}


@app.post("/restart")
def restart_service():
    """Restart the blackbox service"""
    try:
        import subprocess
        # Use systemctl to restart the service
        # Note: This requires passwordless sudo for the restart command
        result = subprocess.run(
            ["sudo", "systemctl", "restart", "blackbox.service"],
            capture_output=True,
            text=True,
            timeout=10
        )

        if result.returncode == 0:
            return {"status": "success", "message": "Service restart initiated"}
        else:
            return {"status": "error", "message": f"Restart failed: {result.stderr}"}
    except subprocess.TimeoutExpired:
        return {"status": "success", "message": "Restart command sent (service restarting)"}
    except Exception as e:
        import traceback
        return {"status": "error", "error": str(e), "trace": traceback.format_exc()}

def _elevenlabs_stream_chunked(text: str, voice: str, model_id: str | None,
                               voice_settings: dict | None):
    """Yield ElevenLabs audio for `text`, splitting by the model's live char cap
    and streaming each chunk's audio (each chunk has its own idle timeout)."""
    from Orchestrator.config import ELEVENLABS_TTS_MODEL_DEFAULT
    from Orchestrator.elevenlabs import tts as el_tts
    cap = el_tts.max_chars_for(model_id or ELEVENLABS_TTS_MODEL_DEFAULT)
    pieces = [text] if len(text) <= cap else chunk_text_for_tts(text, max_chars=cap)
    for piece in pieces:
        yield from el_tts.synthesize_stream(piece, voice, model_id=model_id, voice_settings=voice_settings)


@app.post("/tts")
def tts_openai(body: dict = Body(...)):
    """Text-to-speech using OpenAI TTS API (default) or ElevenLabs.

    ElevenLabs voices (``voice`` prefixed ``elevenlabs:`` OR ``provider ==
    "elevenlabs"``) are handled FIRST and routed through the quality-first
    ``elevenlabs.tts.synthesize`` path -- the OpenAI code below is untouched for
    every non-ElevenLabs voice.

    By default, returns audio stream (for browser compatibility).
    Set return_json=true in body to get JSON with audio_url (for MCP/API use).
    """
    # Scrub non-spoken symbols (markdown asterisks, backticks, pipes, emoji, …) ONCE
    # up front so every provider branch below inherits speech-clean text.
    if isinstance(body, dict) and body.get("text"):
        body["text"] = sanitize_for_speech(body["text"])
    # --- ElevenLabs branch (checked before OpenAI so the OpenAI path is intact) ---
    if (body.get("voice") or "").startswith("elevenlabs:") or body.get("provider") == "elevenlabs":
        text = (body.get("text") or "").strip()
        if not text:
            raise HTTPException(400, "No text provided")
        voice = (body.get("voice") or "").strip()
        model_id = (body.get("model") or "").strip() or None  # None -> synthesize defaults to eleven_v3
        voice_settings = body.get("voice_settings")
        # Browser path: prime the first chunk so an IMMEDIATE failure (bad voice /
        # auth / un-downgradable plan rejection) still returns the structured
        # fallback, then stream the rest. Only a true MID-stream stall truncates.
        if not body.get("return_json"):
            import itertools
            gen = _elevenlabs_stream_chunked(text, voice, model_id, voice_settings)
            try:
                first = next(gen)
            except StopIteration:
                return {"status": "fallback", "detail": "ElevenLabs returned no audio"}
            except Exception as e:
                print(f"[ELEVENLABS] /tts synthesis failed: {e}")
                return {"status": "fallback", "detail": str(e)}
            return StreamingResponse(
                itertools.chain([first], gen),
                media_type="audio/mpeg",
            )

        # MCP/API path: write chunks to the file AS THEY ARRIVE, then return the URL.
        # The provider's per-chunk idle timeout (synthesize_stream) bounds this — no
        # total cap — so a long-but-progressing generation completes instead of being
        # cut at 60s.
        filename = f"{uuid.uuid4()}_tts.mp3"
        save_path = UPLOADS_DIR / filename
        size = 0
        try:
            with open(save_path, "wb") as f:
                for chunk in _elevenlabs_stream_chunked(text, voice, model_id, voice_settings):
                    f.write(chunk)
                    size += len(chunk)
        except Exception as e:
            print(f"[ELEVENLABS] /tts synthesis failed: {e}")
            try:
                save_path.unlink(missing_ok=True)
            except Exception:
                pass
            return {"status": "fallback", "detail": str(e)}
        if size == 0:
            try:
                save_path.unlink(missing_ok=True)
            except Exception:
                pass
            return {"status": "fallback", "detail": "ElevenLabs returned no audio"}
        return {
            "status": "success",
            "audio_url": f"/ui/uploads/{filename}",
            "voice": voice,
            "model": model_id or "eleven_v3",
            "format": "mp3",
            "size_bytes": size,
        }

    # --- Local (custom server) branch: route to the registered Kokoro/Speaches
    # /v1/audio/speech, checked BEFORE the OpenAI path (which rejects Kokoro voice
    # ids with an OpenAI-voice-enum 400). Triggered by a 'local:' voice prefix or
    # provider=='local'. Mirrors the /tts/batch local branch.
    if (body.get("voice") or "").startswith("local:") or body.get("provider") == "local":
        from Orchestrator.onboarding.custom_servers import resolve_audio
        resolved = resolve_audio("tts")
        if not resolved:
            return {"status": "fallback", "message": "no local text-to-speech model available"}
        _srv, _model = resolved
        _text = (body.get("text") or "").strip()
        if not _text:
            raise HTTPException(400, "No text provided")
        _voice = (body.get("voice") or "").strip()
        _bare = _voice.split(":", 1)[1] if _voice.startswith("local:") else (_voice or "af_heart")
        _fmt = (body.get("format") or "mp3").strip()
        _req = {"model": _model, "input": _text, "voice": _bare, "response_format": _fmt}
        _hdr = {"Content-Type": "application/json"}
        if _srv.get("api_key"):
            _hdr["Authorization"] = f"Bearer {_srv['api_key']}"
        try:
            _r = requests.post(f"{_srv['base_url']}/audio/speech", json=_req, headers=_hdr,
                               timeout=TTS_TIMEOUT / 1000.0)
        except Exception as e:
            return {"status": "fallback", "detail": str(e)}
        if _r.status_code != 200:
            return {"status": "fallback", "api_status": _r.status_code, "api_body": _r.text[:400]}
        _mime = {"mp3": "audio/mpeg", "opus": "audio/ogg", "wav": "audio/wav",
                 "flac": "audio/flac", "pcm": "audio/wav"}.get(_fmt, "audio/mpeg")
        if not body.get("return_json"):
            return StreamingResponse(iter([_r.content]), media_type=_mime)
        _ext = {"mp3": ".mp3", "opus": ".ogg", "wav": ".wav", "flac": ".flac", "pcm": ".wav"}.get(_fmt, ".mp3")
        _filename = f"{uuid.uuid4()}_tts{_ext}"
        (UPLOADS_DIR / _filename).write_bytes(_r.content)
        return {"status": "success", "audio_url": f"/ui/uploads/{_filename}",
                "voice": _bare, "model": _model, "format": _fmt, "size_bytes": len(_r.content)}

    # --- On-box Qwen3-TTS branch: route to the llama-swap /v1/audio/speech
    # proxy (body-model auto-routed to the qwen-tts member). Triggered by a
    # 'qwen:' voice prefix or provider=='qwen'. Checked BEFORE the OpenAI path
    # (which rejects Qwen voice tokens with an OpenAI-voice-enum 400). Mirrors
    # the local branch but targets the on-box stack (:9098). sanitize_for_speech
    # already applied up front (line 140).
    if (body.get("voice") or "").startswith("qwen:") or body.get("provider") == "qwen":
        from Orchestrator import qwen_tts
        _text = (body.get("text") or "").strip()
        if not _text:
            raise HTTPException(400, "No text provided")
        _voice = (body.get("voice") or "").strip()
        _bare = _voice.split(":", 1)[1] if _voice.startswith("qwen:") else _voice
        # The on-box Qwen member emits WAV/PCM only (M6 /v1/audio/speech 400s any
        # other response_format — there is no mp3/opus encoder). Always request
        # 'wav' (a proper RIFF container the browser plays directly); ignore any
        # client `format` hint since Qwen cannot honor mp3/opus.
        _fmt = "wav"
        try:
            _r = qwen_tts.synthesize(_bare, _text, response_format=_fmt)
        except Exception as e:
            return {"status": "fallback", "detail": str(e)}
        if _r.status_code != 200:
            return {"status": "fallback", "api_status": _r.status_code,
                    "api_body": _r.text[:400]}
        _mime = "audio/wav"
        if not body.get("return_json"):
            return StreamingResponse(iter([_r.content]), media_type=_mime)
        _filename = f"{uuid.uuid4()}_tts.wav"
        (UPLOADS_DIR / _filename).write_bytes(_r.content)
        return {"status": "success", "audio_url": f"/ui/uploads/{_filename}",
                "voice": _bare, "model": qwen_tts.QWEN_TTS_MODEL, "format": _fmt,
                "size_bytes": len(_r.content)}

    if AUDIO_ENGINE == "browser": return {"status": "fallback"}
    api_key = OPENAI_API_KEY.strip()
    if not api_key: return {"status": "fallback", "message": "OPENAI_API_KEY not configured"}
    text = (body.get("text") or "").strip()
    if not text: raise HTTPException(400, "No text provided")

    audio_format = (body.get("format") or TTS_FORMAT).strip()
    req = {
        "model": (body.get("model") or TTS_MODEL).strip(),
        "input": text,
        "voice": (body.get("voice") or TTS_VOICE).strip(),
        "response_format": audio_format
    }

    try:
        r = requests.post(OPENAI_TTS_URL, json=req, headers={"Authorization": f"Bearer {api_key}"}, timeout=TTS_TIMEOUT/1000.0)
    except Exception as e:
        return {"status":"fallback","detail":str(e)}

    if r.status_code != 200:
        return {"status":"fallback","api_status":r.status_code,"api_body":r.text}

    mime = "audio/mpeg" if audio_format=="mp3" else ("audio/ogg" if audio_format=="opus" else "audio/wav")

    # Default: return audio stream for browser compatibility
    # Only save to file if explicitly requesting JSON response (MCP/API use)
    if not body.get("return_json"):
        return StreamingResponse(iter([r.content]), media_type=mime)

    # Save to file and return URL (for MCP/API use when return_json=true)
    ext = ".mp3" if audio_format == "mp3" else (".ogg" if audio_format == "opus" else ".wav")
    filename = f"{uuid.uuid4()}_tts{ext}"
    save_path = UPLOADS_DIR / filename

    with open(save_path, "wb") as f:
        f.write(r.content)

    audio_url = f"/ui/uploads/{filename}"
    return {
        "status": "success",
        "audio_url": audio_url,
        "voice": req["voice"],
        "model": req["model"],
        "format": audio_format,
        "size_bytes": len(r.content)
    }


# Thread pool for parallel TTS generation (shared across requests)
_tts_executor = ThreadPoolExecutor(max_workers=8)


@app.post("/tts/batch")
async def tts_batch(body: dict = Body(...)):
    """Batch TTS: split text into chunks, generate all in parallel, return combined audio.

    Accepts:
        text (str): Full text to synthesize
        provider (str): "openai", "gemini-pro", "gemini-flash", or "elevenlabs" (default: "openai")
        voice (str): Voice name (default: config TTS_VOICE)
        model (str): Model override (provider-specific)
        format (str): "mp3" or "wav" (default: config TTS_FORMAT)
        operator (str): Operator name for logging
        max_chunk_chars (int): Max characters per chunk (default: 800)
    """
    t_start = time.time()

    # Scrub non-spoken symbols before chunking so every chunk (any provider) is clean.
    text = sanitize_for_speech(body.get("text") or "")
    if not text:
        raise HTTPException(400, "No text provided")

    provider = (body.get("provider") or "openai").strip().lower()
    voice = (body.get("voice") or TTS_VOICE).strip()
    # A local:-prefixed voice forces the local provider (parity with POST /tts), so a
    # caller that passes the voice but omits provider still routes to Kokoro, not OpenAI.
    if voice.startswith("local:"):
        provider = "local"
    # A qwen:-prefixed voice forces the qwen provider (parity with local:), so a
    # caller that passes the prefixed voice but omits provider still routes on-box.
    if voice.startswith("qwen:"):
        provider = "qwen"
    model = (body.get("model") or "").strip()
    audio_format = (body.get("format") or TTS_FORMAT).strip()
    operator = (body.get("operator") or "unknown").strip()
    # Provider-specific chunk defaults: OpenAI is fast per-request, Gemini benefits from smaller chunks
    default_chunk = 1500 if provider == "openai" else 800
    max_chunk_chars = int(body.get("max_chunk_chars", default_chunk))

    # Split text into chunks
    chunks = chunk_text_for_tts(text, max_chars=max_chunk_chars)
    if not chunks:
        raise HTTPException(400, "Text produced no chunks after splitting")

    num_chunks = len(chunks)
    print(f"[TTS Batch] {provider} | {num_chunks} chunks | voice={voice} | format={audio_format} | operator={operator}")

    loop = asyncio.get_running_loop()

    # --- OpenAI provider ---
    if provider == "openai":
        api_key = OPENAI_API_KEY.strip()
        if not api_key:
            raise HTTPException(400, "OPENAI_API_KEY not configured")

        effective_model = model or TTS_MODEL

        def _openai_tts_chunk(chunk_text: str) -> bytes:
            req = {
                "model": effective_model,
                "input": chunk_text,
                "voice": voice,
                "response_format": audio_format,
            }
            r = requests.post(
                OPENAI_TTS_URL,
                json=req,
                headers={"Authorization": f"Bearer {api_key}"},
                timeout=TTS_TIMEOUT / 1000.0,
            )
            if r.status_code != 200:
                raise HTTPException(502, f"OpenAI TTS failed (HTTP {r.status_code}): {r.text[:200]}")
            return r.content

        # Run all chunks in parallel
        futures = [loop.run_in_executor(_tts_executor, _openai_tts_chunk, chunk) for chunk in chunks]
        results = await asyncio.gather(*futures, return_exceptions=True)

    # --- Gemini provider ---
    elif provider in ("gemini-pro", "gemini-flash"):
        def _gemini_tts_chunk(chunk_text: str) -> bytes:
            inp = GeminiProTTSIn(
                text=chunk_text,
                voice_name=voice,
                model=model if model else None,
                operator=operator,
            )
            # call_gemini_tts returns WAV bytes
            return call_gemini_tts(inp)

        futures = [loop.run_in_executor(_tts_executor, _gemini_tts_chunk, chunk) for chunk in chunks]
        results = await asyncio.gather(*futures, return_exceptions=True)

        # Gemini always returns WAV; override format for stitching logic
        audio_format = "wav"

    # --- ElevenLabs provider ---
    elif provider == "elevenlabs":
        from Orchestrator.config import ELEVENLABS_TTS_MODEL_DEFAULT
        from Orchestrator.elevenlabs import tts as el_tts

        # Re-chunk by the model's LIVE per-request cap (not the generic
        # max_chunk_chars used above) so we make the fewest synthesize calls.
        el_model = model or ELEVENLABS_TTS_MODEL_DEFAULT
        cap = el_tts.max_chars_for(el_model)
        chunks = chunk_text_for_tts(text, max_chars=cap)
        num_chunks = len(chunks)
        voice_settings = body.get("voice_settings")

        def _el_tts_chunk(chunk_text: str) -> bytes:
            return el_tts.synthesize(
                chunk_text, voice,
                model_id=model if model else None,
                voice_settings=voice_settings,
            )

        futures = [loop.run_in_executor(_tts_executor, _el_tts_chunk, chunk) for chunk in chunks]
        results = await asyncio.gather(*futures, return_exceptions=True)

        # ElevenLabs returns MP3; concatenated frames play fine (no WAV stitch).
        audio_format = "mp3"

    # --- Local (custom server) provider: /v1/audio/speech, OpenAI-shaped ---
    elif provider == "local":
        from Orchestrator.onboarding.custom_servers import resolve_audio
        resolved = resolve_audio("tts")
        if not resolved:
            raise HTTPException(400, "No local text-to-speech model available (register an OpenAI-compatible server hosting a TTS model)")
        _srv, _model = resolved
        _bare_voice = voice.split(":", 1)[1] if voice.startswith("local:") else voice

        def _local_tts_chunk(chunk_text: str) -> bytes:
            req = {"model": _model, "input": chunk_text, "voice": _bare_voice,
                   "response_format": audio_format}
            headers = {"Content-Type": "application/json"}
            if _srv.get("api_key"):
                headers["Authorization"] = f"Bearer {_srv['api_key']}"
            r = requests.post(f"{_srv['base_url']}/audio/speech", json=req,
                              headers=headers, timeout=TTS_TIMEOUT / 1000.0)
            if r.status_code != 200:
                raise HTTPException(502, f"Local TTS failed (HTTP {r.status_code}): {r.text[:200]}")
            return r.content

        futures = [loop.run_in_executor(_tts_executor, _local_tts_chunk, chunk) for chunk in chunks]
        results = await asyncio.gather(*futures, return_exceptions=True)

    # --- On-box Qwen3-TTS provider: llama-swap /v1/audio/speech, sequential ---
    elif provider == "qwen":
        from Orchestrator import qwen_tts
        _bare = voice.split(":", 1)[1] if voice.startswith("qwen:") else voice

        def _qwen_all() -> List[bytes]:
            # Sequential on purpose: one GPU serializes synthesis anyway, and
            # the qwen-tts member's concurrencyLimit:2 would 429 a parallel
            # fan-out. Any non-200 raises -> the endpoint returns 502.
            # Request WAV: the M6 server emits WAV/PCM only (it 400s mp3/opus —
            # there is no encoder), so audio_format cannot flow through here.
            out: List[bytes] = []
            for ch in chunks:
                r = qwen_tts.synthesize(_bare, ch, response_format="wav")
                if r.status_code != 200:
                    raise HTTPException(502, f"Qwen TTS failed (HTTP {r.status_code}): {r.text[:200]}")
                out.append(r.content)
            return out

        results = await loop.run_in_executor(_tts_executor, _qwen_all)
        # Qwen returns WAV — drive the WAV stitcher + audio/wav mime below
        # (mirrors the Gemini branch's `audio_format = "wav"`).
        audio_format = "wav"

    else:
        raise HTTPException(400, f"Unknown provider: {provider}. Use 'openai', 'gemini-pro', 'gemini-flash', 'elevenlabs', 'local', or 'qwen'.")

    # Check for errors in results
    errors = [(i, r) for i, r in enumerate(results) if isinstance(r, Exception)]
    if errors:
        err_idx, err = errors[0]
        print(f"[TTS Batch] ERROR on chunk {err_idx}/{num_chunks}: {err}")
        raise HTTPException(502, f"TTS failed on chunk {err_idx + 1}/{num_chunks}: {err}")

    audio_chunks: List[bytes] = list(results)  # type: ignore[arg-type]

    # Stitch results
    if audio_format == "wav":
        combined = stitch_wav_chunks(audio_chunks)
    else:
        # MP3/opus: simple byte concatenation (frames are self-delimiting)
        combined = b"".join(audio_chunks)

    elapsed = time.time() - t_start
    mime = "audio/mpeg" if audio_format == "mp3" else ("audio/ogg" if audio_format == "opus" else "audio/wav")
    print(f"[TTS Batch] Done: {num_chunks} chunks, {len(combined)} bytes, {elapsed:.2f}s | {mime}")

    return StreamingResponse(iter([combined]), media_type=mime)


@app.post("/tts/stitch")
async def tts_stitch(chunks: List[UploadFile] = File(...)):
    """Stitch multiple WAV file chunks into a single combined WAV file.

    Accepts multipart form data with one or more WAV file uploads.
    Uses proper WAV header/frame stitching to avoid audio artifacts.
    """
    if not chunks:
        raise HTTPException(400, "No files provided")

    wav_chunks: List[bytes] = []
    for f in chunks:
        data = await f.read()
        if not data:
            continue
        wav_chunks.append(data)

    if not wav_chunks:
        raise HTTPException(400, "All uploaded files were empty")

    print(f"[TTS Stitch] Stitching {len(wav_chunks)} WAV chunks")
    combined = stitch_wav_chunks(wav_chunks)
    print(f"[TTS Stitch] Result: {len(combined)} bytes")

    return StreamingResponse(iter([combined]), media_type="audio/wav")


@app.post("/stt")
async def stt(
    file: UploadFile = File(...),
    provider: str = Form(None),
    diarize: bool = Form(False),
):
    from Orchestrator.stt.file_transcribe import transcribe_bytes
    from Orchestrator.stt.resolve import resolve_stt_provider
    try:
        audio_bytes = await file.read()
    except Exception as e:
        raise HTTPException(400, f"Failed to read upload: {e}")

    filename = file.filename or "audio.webm"
    content_type = file.content_type or "audio/webm"

    # Diarized rich payload only when ElevenLabs is the resolved provider AND the
    # caller explicitly asked for diarization. Back-compat: flat `text` stays at
    # the top level so existing single-field consumers keep working unchanged.
    resolved = (provider or "").strip().lower() or resolve_stt_provider()
    if resolved == "elevenlabs" and diarize:
        from Orchestrator.elevenlabs import stt as el_stt
        try:
            rich = el_stt.transcribe_bytes(audio_bytes, filename, diarize=True)
        except RuntimeError as e:
            raise HTTPException(400, str(e))
        except Exception as e:
            raise HTTPException(502, f"STT upstream error: {e}")
        return {
            "text": rich["text"],                # BACK-COMPAT: flat text top-level
            "provider": "elevenlabs",
            "segments": rich["segments"],
            "speakers": rich["speakers"],
            "diarized_text": el_stt.format_diarized(rich),
            "events": rich["events"],
            "language": rich["language"],
        }

    try:
        text = transcribe_bytes(
            audio_bytes,
            content_type,
            provider=provider,
            filename=filename,
        )
    except RuntimeError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        raise HTTPException(502, f"STT upstream error: {e}")
    return {"text": text}


@app.post("/stt/json")
async def stt_json(body: dict = Body(...)):
    """
    Speech-to-text from JSON with base64-encoded PCM16 audio.
    Used by Portal's Gemini Live to transcribe user audio (since Gemini doesn't provide user_transcript).

    Body:
        audio: base64-encoded PCM16 audio data
        sample_rate: sample rate (default 16000)
        format: 'pcm16' (default)
    """
    from Orchestrator.stt.file_transcribe import transcribe_bytes

    audio_b64 = body.get("audio")
    if not audio_b64:
        raise HTTPException(400, "Missing 'audio' field (base64 PCM16)")

    sample_rate = body.get("sample_rate", 16000)

    try:
        # Decode base64 to PCM16 bytes
        pcm_bytes = base64.b64decode(audio_b64)

        if len(pcm_bytes) < 100:
            # Too short to transcribe
            return {"text": ""}

        # Convert PCM16 to WAV format (Whisper needs proper audio container)
        wav_buffer = io.BytesIO()
        with wave.open(wav_buffer, 'wb') as wav_file:
            wav_file.setnchannels(1)  # Mono
            wav_file.setsampwidth(2)  # 16-bit
            wav_file.setframerate(sample_rate)
            wav_file.writeframes(pcm_bytes)

        wav_bytes = wav_buffer.getvalue()
        print(f"[STT/JSON] Converting {len(pcm_bytes)} bytes PCM16 -> {len(wav_bytes)} bytes WAV @ {sample_rate}Hz")

    except Exception as e:
        raise HTTPException(400, f"Failed to decode/convert audio: {e}")

    # Transcribe via resolved provider (OpenAI, Google, or ElevenLabs). Flat text
    # only — this path serves Gemini Live quick transcription; diarization (YAGNI
    # here) lives on /stt. An explicit provider in the body is honored.
    try:
        text = transcribe_bytes(
            wav_bytes, "audio/wav", provider=body.get("provider"), filename="audio.wav"
        )
    except RuntimeError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        raise HTTPException(502, f"STT upstream error: {e}")

    print(f"[STT/JSON] Transcription: '{text[:100]}...' ({len(text)} chars)")
    return {"text": text}


@app.post("/stt/translate")
async def stt_translate(body: dict = Body(...)):
    """Any-target translation. Body: {text?, audio? (base64), content_type?, target_lang}.
    If audio is given, it is transcribed first (resolved STT provider) then translated."""
    from Orchestrator.stt.translate import translate_text
    target_lang = (body.get("target_lang") or "").strip()
    if not target_lang:
        raise HTTPException(400, "target_lang required")
    text = body.get("text")
    if not text and body.get("audio"):
        import base64 as _b64
        from Orchestrator.stt.file_transcribe import transcribe_bytes
        try:
            audio_bytes = _b64.b64decode(body["audio"])
            text = transcribe_bytes(audio_bytes, body.get("content_type") or "audio/wav", filename="audio.wav")
        except RuntimeError as e:
            raise HTTPException(400, str(e))
        except Exception as e:
            raise HTTPException(502, f"STT upstream error: {e}")
    try:
        translated = translate_text(text or "", target_lang)
    except RuntimeError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        raise HTTPException(502, f"Translate error: {e}")
    return {"text": translated, "target_lang": target_lang}

# -----------------------------------------------------------------------------
# Generative Endpoints - Nano Banana Pro (Gemini Image Generation)
# -----------------------------------------------------------------------------
def call_imagen(prompt: str, model: str, options: dict = None) -> list:
    """
    Calls Gemini Image Generation API (Nano Banana Pro) and returns image bytes.
    Uses generateContent endpoint with IMAGE response modality.

    Args:
        prompt: Text prompt for image generation
        model: Model to use (e.g., gemini-2.0-flash-exp-image-generation)
        options: Optional dict with:
            - aspectRatio: "1:1", "16:9", "9:16", etc. (default "16:9")
            - resolution: "1K", "2K", "4K" (default "1K")
            - numberOfImages: 1-4 (default 1)
            - referenceImages: List of {data, mimeType} for style guidance

    Returns:
        List of image bytes (one per generated image)
    """
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=400, detail="GOOGLE_API_KEY not configured for image generation.")

    options = options or {}
    aspect_ratio = options.get("aspectRatio", "16:9")
    resolution = options.get("resolution", "1K")
    # Gemini imageConfig.imageSize only accepts 1K/2K/4K. GenIn.resolution is shared
    # with video (defaults like "720p"/"1080p"), so coerce any non-image value to 1K
    # to avoid an INVALID_ARGUMENT 400 from a stray video resolution.
    if resolution not in ("1K", "2K", "4K"):
        resolution = "1K"
    num_images = min(max(int(options.get("numberOfImages", 1)), 1), 4)  # Clamp 1-4
    reference_images = options.get("referenceImages", [])

    # Build content parts - reference images FIRST, then text prompt
    # This follows the multimodal conversation pattern where images come before the question
    parts = []

    # Add reference images if provided (up to 14) - images come first
    for ref_img in reference_images[:14]:
        if ref_img.get("data") and ref_img.get("mimeType"):
            parts.append({
                "inlineData": {
                    "mimeType": ref_img["mimeType"],
                    "data": ref_img["data"]
                }
            })

    # Add text prompt after images
    parts.append({"text": prompt})

    # Key goes in the x-goog-api-key HEADER (not the URL) so it can never leak into
    # error strings / logs on a non-200, and to match the documented auth path.
    url = f"{GEMINI_BASE_URL}/{model}:generateContent"
    gemini_headers = {"x-goog-api-key": GOOGLE_API_KEY, "Content-Type": "application/json"}

    # Build generation config with Nano Banana Pro options
    # Note: responseModalities tells Gemini to return images
    # Image options go in imageConfig, not directly in generationConfig
    generation_config = {
        "responseModalities": ["TEXT", "IMAGE"],
        "imageConfig": {
            "aspectRatio": aspect_ratio,
            "imageSize": resolution  # 1K, 2K, or 4K
        }
    }

    payload = {
        "contents": [{"parts": parts}],
        "generationConfig": generation_config
    }

    try:
        print(f"[IMAGE GEN] Using model: {model}")
        print(f"[IMAGE GEN] Prompt: {prompt[:100]}...")
        print(f"[IMAGE GEN] Options: aspect={aspect_ratio}, resolution={resolution}, count={num_images}, refs={len(reference_images)}")

        images = []

        # Generate requested number of images
        for i in range(num_images):
            print(f"[IMAGE GEN] Generating image {i+1}/{num_images}...")
            response = requests.post(url, headers=gemini_headers, json=payload, timeout=400)

            # Log response details for debugging
            if response.status_code != 200:
                print(f"[IMAGE GEN] API Error {response.status_code}: {response.text[:500]}")

            response.raise_for_status()
            data = response.json()

            # Parse the Gemini generateContent response format
            if "candidates" in data and data["candidates"]:
                resp_parts = data["candidates"][0].get("content", {}).get("parts", [])
                for part in resp_parts:
                    if "inlineData" in part:
                        b64_string = part["inlineData"].get("data")
                        if b64_string:
                            print(f"[IMAGE GEN] Got image {i+1}")
                            images.append(base64.b64decode(b64_string))
                            break

            # Check for safety blocks
            if "promptFeedback" in data:
                feedback = data["promptFeedback"]
                if feedback.get("blockReason"):
                    raise HTTPException(status_code=400, detail=f"Image generation blocked: {feedback.get('blockReason')}")

        if not images:
            raise HTTPException(status_code=500, detail=f"No images in response from Gemini API: {data}")

        print(f"[IMAGE GEN] Success! Generated {len(images)} image(s)")
        return images

    except requests.exceptions.HTTPError as e:
        # Log the actual error response from API
        error_detail = ""
        try:
            error_detail = e.response.text[:1000] if e.response else str(e)
        except:
            error_detail = str(e)
        print(f"[IMAGE GEN] HTTP Error: {error_detail}")
        raise HTTPException(status_code=502, detail=f"Gemini Image API request failed: {error_detail}")
    except requests.exceptions.RequestException as e:
        print(f"[IMAGE GEN] Request error: {e}")
        raise HTTPException(status_code=502, detail=f"Gemini Image API request failed: {e}")

@app.post("/generate/image")
async def generate_image(inp: GenIn):
    """Queue image generation task with Nano Banana Pro options"""
    try:
        # Build image generation options
        image_options = {
            "aspectRatio": inp.aspectRatio or "16:9",
            "resolution": inp.resolution or "1K",
            "numberOfImages": inp.numberOfImages or 1,
        }

        # Add reference images if provided
        if inp.referenceImages:
            image_options["referenceImages"] = [
                {"data": ref.data, "mimeType": ref.mimeType}
                for ref in inp.referenceImages
            ]

        # OpenAI gpt-image params -- copy through so they reach _openai_images via
        # result_data["options"]. (gemini/grok ignore these; harmless if present.)
        if inp.size:
            image_options["size"] = inp.size
        if inp.quality:
            image_options["quality"] = inp.quality

        # Route to a per-provider adapter when specified (default = gemini in worker)
        if inp.provider:
            image_options["provider"] = inp.provider

        task = create_task(
            TaskType.IMAGE_GENERATION,
            operator=inp.operator,
            prompt=inp.prompt,
            result_data={"options": image_options}  # Store options for worker
        )

        img_count = inp.numberOfImages or 1
        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": f"Image generation queued ({img_count} image{'s' if img_count > 1 else ''} @ {inp.resolution or '1K'})"
        }
    except Exception as e:
        print(f"ERROR: Failed to queue image generation: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/image/catalog")
async def image_catalog():
    """Enabled image providers + their param schema -- the param SoT both the
    Portal and Android image UIs hydrate from."""
    from Orchestrator.image_catalog import build_image_catalog
    return {"providers": build_image_catalog()}

@app.post("/generate/video")
async def generate_video(inp: GenIn):
    """Queue Veo 3.1 video generation task (text-to-video or image-to-video)

    Supports image-to-video via:
    - image: ImageData with base64 data and mime_type
    - image_url: URL path like /ui/uploads/image.png (will be converted to base64)
    """
    import base64
    from pathlib import Path

    try:
        # Prepare image data if provided
        image_data = None
        source_image_url = None

        # Option 1: Direct base64 image data
        if inp.image:
            image_data = {
                "data": inp.image.data,
                "mime_type": inp.image.mime_type
            }

        # Option 2: Image URL - convert to base64
        elif inp.image_url:
            source_image_url = inp.image_url

            # Clean URL - remove host prefix if present
            clean_url = inp.image_url
            if clean_url.startswith("http://") or clean_url.startswith("https://"):
                from urllib.parse import urlparse
                parsed = urlparse(clean_url)
                clean_url = parsed.path

            # Resolve to file path: /ui/uploads/file.png -> Portal/uploads/file.png
            if clean_url.startswith("/ui/"):
                relative_path = clean_url.replace("/ui/", "")
                file_path = Path("Portal") / relative_path

                if not file_path.exists():
                    raise HTTPException(status_code=404, detail=f"Image file not found: {clean_url}")

                # Read and encode file
                with open(file_path, "rb") as f:
                    image_bytes = f.read()
                image_b64 = base64.b64encode(image_bytes).decode()

                # Determine MIME type from extension
                ext = file_path.suffix.lower()
                mime_map = {
                    ".png": "image/png",
                    ".jpg": "image/jpeg",
                    ".jpeg": "image/jpeg",
                    ".gif": "image/gif",
                    ".webp": "image/webp"
                }
                mime_type = mime_map.get(ext, "image/jpeg")

                image_data = {
                    "data": image_b64,
                    "mime_type": mime_type
                }
                print(f"[VIDEO] Converted image_url to base64: {clean_url} ({len(image_bytes)} bytes, {mime_type})")
            else:
                raise HTTPException(status_code=400, detail=f"Invalid image_url format: {inp.image_url}")

        # Parse duration - support both 'duration' (int) and legacy 'durationSeconds' (str)
        duration = inp.duration or 8
        if inp.durationSeconds and not inp.duration:
            duration = int(inp.durationSeconds)

        # Store video options in result_data for the worker to use
        video_options = {
            "aspectRatio": inp.aspectRatio or "16:9",
            "resolution": inp.resolution or "720p",
            "duration": duration,
            "negativePrompt": inp.negativePrompt
        }

        # Store source image URL for reference if used
        if source_image_url:
            video_options["source_image_url"] = source_image_url

        task = create_task(
            TaskType.VIDEO_GENERATION,
            operator=inp.operator,
            prompt=inp.prompt,
            image_data=image_data,
            result_data=video_options  # Pass video options to worker
        )

        mode = "image-to-video" if image_data else "text-to-video"
        res_str = inp.resolution or "720p"
        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": f"Video generation ({mode}, {duration}s @ {res_str}) queued (Veo 3.1 - may take 5-20 minutes)",
            "source_image": source_image_url
        }
    except HTTPException:
        raise
    except Exception as e:
        print(f"ERROR: Failed to queue video generation: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/extend/video")
async def extend_video(inp: VideoExtensionIn):
    """Queue Veo 3.1 video extension task"""
    try:
        # Store video URL for extension
        video_data = {
            "url": inp.video_url,
            "prompt": inp.prompt
        }

        task = create_task(
            TaskType.VIDEO_GENERATION,
            operator=inp.operator,
            prompt=inp.prompt or "Extend video",
            result_data=video_data  # Store video URL for worker to use
        )

        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": "Video extension queued (Veo 3.1 - may take 5-20 minutes)"
        }
    except Exception as e:
        print(f"ERROR: Failed to queue video extension: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# -----------------------------------------------------------------------------
# Google TTS Endpoints (Tool #1: Cloud SSML)
# -----------------------------------------------------------------------------

def call_google_tts_voices() -> Dict[str, Any]:
    """Calls Google TTS API to get the list of voices."""
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=400, detail="GOOGLE_API_KEY not configured.")
    url = f"{GOOGLE_TTS_VOICES_URL}?key={GOOGLE_API_KEY}"
    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"ERROR: Failed to fetch Google voices: {e}")
        # Pass the error message to the client
        raise HTTPException(status_code=e.response.status_code if e.response else 502, detail=str(e))

def call_google_tts_synthesize(inp: GoogleSSMLIn) -> bytes:
    """Calls Google TTS API to synthesize speech."""
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=400, detail="GOOGLE_API_KEY not configured.")

    url = f"{GOOGLE_TTS_SYNTHESIZE_URL}?key={GOOGLE_API_KEY}"

    # --- FIX: Add languageCode to the voice object ---
    # Extract language code from the voice name (e.g., "en-US" from "en-US-Wavenet-F")
    lang_code = "-".join(inp.voice_name.split("-")[:2])
    if not lang_code:
        raise HTTPException(status_code=400, detail="Invalid voice name, could not determine language code.")

    # Validate and clamp pitch and speaking rate to Google's acceptable ranges
    # Pitch: -20.0 to +20.0 semitones
    # Speaking rate: 0.25 to 4.0
    pitch = max(-20.0, min(20.0, float(inp.pitch)))
    speaking_rate = max(0.25, min(4.0, float(inp.speaking_rate)))

    payload = {
        "voice": {
            "name": inp.voice_name,
            "languageCode": lang_code  # <-- THE FIX
        },
        "audioConfig": {
            "audioEncoding": "MP3",
            "speakingRate": speaking_rate,
            "pitch": pitch
        }
    }

    if inp.ssml:
        # Ensure SSML is wrapped in <speak> tags if not already
        ssml_text = inp.ssml.strip()
        if not ssml_text.startswith("<speak"):
            ssml_text = f"<speak>{ssml_text}</speak>"
        payload["input"] = {"ssml": ssml_text}
    elif inp.text:
        # Plain-text branch only — never touch the SSML branch above (would strip <speak>).
        payload["input"] = {"text": sanitize_for_speech(inp.text)}
    else:
        raise HTTPException(status_code=400, detail="Either 'text' or 'ssml' must be provided.")

    # DEBUG: Log the request payload (without API key)
    print(f"[GOOGLE TTS] Request payload: {json.dumps(payload, indent=2)}")

    try:
        response = requests.post(url, json=payload, timeout=400)
        response.raise_for_status()
        data = response.json()
        if "audioContent" in data:
            print(f"[GOOGLE TTS] Success! Audio generated.")
            return base64.b64decode(data["audioContent"])
        raise HTTPException(status_code=500, detail=f"Invalid response from Google TTS API: {data}")
    except requests.exceptions.RequestException as e:
        error_detail = str(e)
        full_error = None
        try:
            # Try to parse the error response from Google
            if hasattr(e, 'response') and e.response is not None:
                full_error = e.response.json()
                error_detail = full_error.get("error", {}).get("message", e.response.text)
                print(f"[GOOGLE TTS ERROR] Full error response: {json.dumps(full_error, indent=2)}")
        except Exception:
            pass # Keep the original error string
        print(f"[GOOGLE TTS ERROR] Failed: {error_detail}")
        raise HTTPException(status_code=e.response.status_code if hasattr(e, 'response') and e.response else 502, detail=f"Google TTS API error: {error_detail}")


@app.get("/tts/google/voices")
async def get_google_voices(operator: Optional[str] = None):
    # We can log this request or check operator permissions if needed
    # op = (operator or CURRENT_OPERATOR or USERS_DEFAULT).strip()
    try:
        return call_google_tts_voices()
    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/tts/catalog")
async def tts_catalog():
    """Grouped TTS voice catalog -- single source of truth for the voice picker
    (web Portal + Android both fetch this). See config.build_tts_catalog().

    When an ElevenLabs key is configured, a 4th dynamic group ("ElevenLabs") is
    APPENDED from the live voice catalog: My Voices first (star-prefixed), then
    Premade. Fail-open -- if the catalog is unreachable the group is simply
    absent and the three static groups are returned unchanged."""
    from Orchestrator.config import build_tts_catalog
    groups = build_tts_catalog()
    try:
        from Orchestrator.elevenlabs import catalog as el_catalog
        v = el_catalog.get_voices()
        if v:
            my = [dict(x, name=f"⭐ {x['name']}") for x in v["my_voices"]]  # star-prefix My Voices
            voices = my + v["premade"]
            if voices:
                groups.append({"id": "elevenlabs", "label": "ElevenLabs", "dynamic": True, "voices": voices})
    except Exception:
        pass  # fail-open: ElevenLabs group simply absent if catalog unreachable
    # Local (custom-server) TTS group — appended when a registered server hosts a
    # text-to-speech model. Fail-open, same as ElevenLabs.
    try:
        from Orchestrator.onboarding.custom_servers import (
            has_audio, resolve_audio, list_local_tts_voices)
        if has_audio("tts"):
            resolved = resolve_audio("tts")
            if resolved:
                _srv, _m = resolved
                voices = list_local_tts_voices(_srv)
                groups.append({"id": "local", "label": "Local (free)", "dynamic": True,
                               "voices": [{"id": f"local:{v}", "name": v,
                                           "description": "Local TTS"} for v in voices]})
    except Exception:
        pass  # fail-open
    # On-box Qwen3-TTS group — present only when the local stack is healthy and
    # TTS is enabled (fail-open, same as the ElevenLabs/local groups above).
    try:
        from Orchestrator import qwen_tts
        _qg = qwen_tts.catalog_group()
        if _qg:
            groups.append(_qg)
    except Exception:
        pass  # fail-open: qwen group simply absent if the helper errors
    return {"groups": groups}


# =============================================================================
# Qwen3-TTS voice management (backs the Voice Lab Qwen tab). Clone/design/save
# proxy /upstream/qwen-tts/v1/voices/… (NON-OpenAI paths llama-swap won't
# auto-route, §5.4); list/delete are filesystem ops over Manifest/voices/qwen/.
# =============================================================================
@app.get("/qwen/voices")
async def qwen_voices_list():
    """Saved clone/design profiles for the manage zone. No GPU wake (disk read)."""
    from Orchestrator import qwen_tts
    return {"voices": qwen_tts.list_profiles()}


@app.post("/qwen/voices/clone")
async def qwen_voices_clone(
    name: str = Form(...),
    consent: str = Form(None),
    description: str = Form(None),
    files: List[UploadFile] = File(...),
):
    """Clone a voice from reference audio (~3s min). Requires the literal
    consent flag — 422 without it, mirroring the ElevenLabs gate. Forwards the
    multipart to the qwen-tts server via /upstream/qwen-tts/v1/voices/clone."""
    if (consent or "").strip().lower() != "true":
        raise HTTPException(422, "consent required to clone a voice")
    from Orchestrator import qwen_tts
    # Forward under the SINGULAR field name 'file' — the M6 server declares
    # `file: UploadFile = File(...)` (Task 6.6), so forwarding 'files' (plural)
    # would 422 the member (missing required 'file'). The proxy still accepts a
    # list from the browser (a single reference clip is the norm) and forwards
    # each part as 'file'.
    fwd_files = []
    for f in files:
        fwd_files.append(("file", (f.filename or "clip.wav", await f.read(),
                                   f.content_type or "application/octet-stream")))
    data = {"name": name, "consent": "true"}
    if description:
        data["description"] = description
    try:
        r = requests.post(qwen_tts.upstream_url("/v1/voices/clone"),
                          data=data, files=fwd_files,
                          timeout=qwen_tts.QWEN_TTS_TIMEOUT)
    except Exception as e:
        raise HTTPException(502, f"qwen-tts clone unreachable: {e}")
    if r.status_code != 200:
        raise HTTPException(r.status_code, r.text[:400])
    return r.json()


@app.post("/qwen/voices/design")
async def qwen_voices_design(body: dict = Body(...)):
    """Design→preview: {voice_description, text?} -> {previews:[{generated_voice_id,
    audio_b64, sample_rate}]} (passed through verbatim; the Voice Lab builds the
    data: URL from audio_b64). Proxied through /upstream/qwen-tts/v1/voices/design."""
    from Orchestrator import qwen_tts
    try:
        r = requests.post(qwen_tts.upstream_url("/v1/voices/design"),
                          json=body, timeout=qwen_tts.QWEN_TTS_TIMEOUT)
    except Exception as e:
        raise HTTPException(502, f"qwen-tts design unreachable: {e}")
    if r.status_code != 200:
        raise HTTPException(r.status_code, r.text[:400])
    return r.json()


@app.post("/qwen/voices/design/save")
async def qwen_voices_design_save(body: dict = Body(...)):
    """Save a chosen design preview: {generated_voice_id, name, description?}
    -> {voice_id}. Persists Manifest/voices/qwen/{slug}/ server-side."""
    from Orchestrator import qwen_tts
    try:
        r = requests.post(qwen_tts.upstream_url("/v1/voices/design/save"),
                          json=body, timeout=qwen_tts.QWEN_TTS_TIMEOUT)
    except Exception as e:
        raise HTTPException(502, f"qwen-tts design/save unreachable: {e}")
    if r.status_code != 200:
        raise HTTPException(r.status_code, r.text[:400])
    return r.json()


@app.delete("/qwen/voices/{slug}")
async def qwen_voices_delete(slug: str):
    """Delete a saved profile (filesystem op; voices are lazy-loaded from disk,
    so no server round-trip is needed)."""
    from Orchestrator import qwen_tts
    if qwen_tts.delete_profile(slug):
        return {"ok": True, "slug": slug}
    raise HTTPException(404, f"no such qwen voice profile: {slug}")


@app.get("/stt/catalog")
async def stt_catalog():
    """STT provider/capability catalog -- single source of truth for the STT
    provider picker (onboarding + Portal + Android). See Orchestrator/stt/catalog."""
    from Orchestrator import config as _cfg
    from Orchestrator.stt.catalog import build_stt_catalog
    from Orchestrator.stt.resolve import resolve_stt_provider
    resolved = resolve_stt_provider()
    return {"providers": build_stt_catalog(), "resolved": resolved,
            "default": _cfg.STT_PROVIDER or resolved}

@app.get("/api/last-response")
async def get_last_response(operator: str):
    """
    Get the most recent assistant response for the given operator from the latest snapshot.
    Used for recovering incomplete conversations after page reload/rotation.
    """
    try:
        # Load the snapshot index
        index = load_snapshot_index()

        # Filter snapshots for this operator and sort by timestamp (newest first)
        operator_snaps = {
            snap_id: meta for snap_id, meta in index.items()
            if meta.get("operator") == operator
        }

        if not operator_snaps:
            raise HTTPException(404, f"No snapshots found for operator: {operator}")

        # Get the most recent snapshot
        latest_snap_id = max(
            operator_snaps.keys(),
            key=lambda sid: operator_snaps[sid].get("timestamp", "")
        )
        latest_meta = operator_snaps[latest_snap_id]

        # Read the snapshot from volume file using byte offsets
        byte_start = latest_meta["byte_start"]
        byte_end = latest_meta["byte_end"]

        with open(VOL_PATH, 'r', encoding='utf-8') as f:
            f.seek(byte_start)
            snapshot_text = f.read(byte_end - byte_start)

        # Parse the Raw Session Log section to extract conversation turns
        # Format: - [N] YYYY-MM-DDTHH:MM:SS.sssZ operator=Name role: message
        log_section_match = re.search(
            r'Raw Session Log\n(.*?)\n(?:Release Notes|===\s+END\s+SNAPSHOT)',
            snapshot_text,
            re.DOTALL
        )

        if not log_section_match:
            raise HTTPException(404, "No conversation log found in snapshot")

        log_section = log_section_match.group(1)

        # Extract all conversation lines
        # Pattern: - [N] timestamp operator=Name role: message
        log_lines = re.findall(
            r'-\s+\[\d+\]\s+\S+\s+operator=\S+\s+(user|assistant):\s+(.+)',
            log_section
        )

        if not log_lines:
            raise HTTPException(404, "No conversation turns found in snapshot")

        # Find the last assistant message
        last_assistant_msg = None
        for role, message in reversed(log_lines):
            if role == "assistant":
                last_assistant_msg = message.strip()
                break

        if not last_assistant_msg:
            raise HTTPException(404, "No assistant response found in snapshot")

        return {
            "success": True,
            "operator": operator,
            "snapshot_id": latest_snap_id,
            "timestamp": latest_meta.get("timestamp"),
            "response": last_assistant_msg
        }

    except HTTPException:
        raise
    except Exception as e:
        print(f"[ERROR] Failed to retrieve last response: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(500, f"Failed to retrieve last response: {str(e)}")

@app.post("/generate/google_ssml")  # Note: renamed from /generate/ssml
async def generate_google_ssml_async(inp: GoogleSSMLIn):
    """Queue Google TTS generation"""
    try:
        task = create_task(
            TaskType.GOOGLE_TTS,
            operator=inp.operator,
            result_data=inp.dict()
        )
        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": "Google TTS generation queued"
        }
    except Exception as e:
        print(f"ERROR: Failed to queue Google TTS: {e}")
        raise HTTPException(status_code=500, detail=str(e))



# -----------------------------------------------------------------------------
# NEW: Gemini Pro TTS (Tool #2)
# -----------------------------------------------------------------------------

def pcm_to_wav(
    pcm_data: bytes,
    sample_width: int,
    frame_rate: int,
    num_channels: int
) -> bytes:
    """
    Converts raw PCM data to a WAV file in memory.
    This version assumes sample_width is 2 (16-bit) and does NOT use audioop.
    """
    # We expect 16-bit (2-byte) audio from Gemini TTS
    if sample_width != 2:
        raise ValueError(f"Expected 16-bit (2-byte) sample width for WAV conversion, but got {sample_width}")

    with io.BytesIO() as wav_buffer:
        with wave.open(wav_buffer, "wb") as wf:
            wf.setnchannels(num_channels)
            wf.setsampwidth(sample_width) # This will be 2
            wf.setframerate(frame_rate)
            wf.writeframes(pcm_data) # Use pcm_data directly
        wav_bytes = wav_buffer.getvalue()
    return wav_bytes


def chunk_text_for_tts(text: str, max_chars: int = 800) -> List[str]:
    """Split text into chunks at sentence boundaries, each under max_chars.

    Uses sentence-ending punctuation and paragraph breaks as split points.
    Falls back to word-level splitting for sentences longer than max_chars.
    """
    if not text or not text.strip():
        return []

    text = text.strip()
    if len(text) <= max_chars:
        return [text]

    # Split at sentence boundaries (.!?) or paragraph breaks
    sentences = re.split(r'(?<=[.!?])\s+|(?<=\n)\n', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    chunks: List[str] = []
    current_chunk = ""

    for sentence in sentences:
        # If this single sentence exceeds max_chars, split at word level
        if len(sentence) > max_chars:
            # Flush current chunk first
            if current_chunk:
                chunks.append(current_chunk.strip())
                current_chunk = ""
            # Word-level splitting for long sentences
            words = sentence.split()
            word_chunk = ""
            for word in words:
                candidate = f"{word_chunk} {word}".strip() if word_chunk else word
                if len(candidate) <= max_chars:
                    word_chunk = candidate
                else:
                    if word_chunk:
                        chunks.append(word_chunk)
                    word_chunk = word
            if word_chunk:
                current_chunk = word_chunk
            continue

        # Try appending sentence to current chunk
        candidate = f"{current_chunk} {sentence}".strip() if current_chunk else sentence
        if len(candidate) <= max_chars:
            current_chunk = candidate
        else:
            # Current chunk is full, start a new one
            if current_chunk:
                chunks.append(current_chunk.strip())
            current_chunk = sentence

    # Don't forget the last chunk
    if current_chunk and current_chunk.strip():
        chunks.append(current_chunk.strip())

    return chunks


def stitch_wav_chunks(wav_chunks: List[bytes]) -> bytes:
    """Combine multiple WAV byte buffers into a single WAV file.

    Reads WAV params from the first chunk and concatenates raw PCM frames
    from all chunks. This avoids audio artifacts from naive byte concatenation.
    """
    if not wav_chunks:
        return b""
    if len(wav_chunks) == 1:
        return wav_chunks[0]

    # Read params from the first chunk
    first_buf = io.BytesIO(wav_chunks[0])
    with wave.open(first_buf, "rb") as wf:
        params = wf.getparams()
        all_frames = wf.readframes(wf.getnframes())

    # Read PCM frames from remaining chunks
    for chunk_bytes in wav_chunks[1:]:
        buf = io.BytesIO(chunk_bytes)
        with wave.open(buf, "rb") as wf:
            all_frames += wf.readframes(wf.getnframes())

    # Write combined WAV
    out_buf = io.BytesIO()
    with wave.open(out_buf, "wb") as wf:
        wf.setparams(params)
        wf.writeframes(all_frames)
    return out_buf.getvalue()


def _get_cloud_tts_access_token() -> str:
    """Get access token from service account for Cloud TTS API."""
    if not GOOGLE_AUTH_AVAILABLE:
        raise HTTPException(status_code=500, detail="google-auth library not installed")
    if not GOOGLE_APPLICATION_CREDENTIALS:
        raise HTTPException(status_code=400, detail="GOOGLE_APPLICATION_CREDENTIALS not configured")

    credentials = service_account.Credentials.from_service_account_file(
        GOOGLE_APPLICATION_CREDENTIALS,
        scopes=["https://www.googleapis.com/auth/cloud-platform"]
    )
    credentials.refresh(GoogleAuthRequest())
    return credentials.token


def call_gemini_tts_cloud(inp: GeminiProTTSIn) -> bytes:
    """Calls Gemini TTS via Cloud Text-to-Speech API (GA models).
    Uses service account authentication and the GA model names:
    - gemini-2.5-pro-tts (high quality)
    - gemini-2.5-flash-tts (lower latency)
    """
    access_token = _get_cloud_tts_access_token()

    # Use model from input, default to pro if not specified or invalid
    valid_models = ["gemini-2.5-pro-tts", "gemini-2.5-flash-tts"]
    model_name = inp.model if inp.model in valid_models else "gemini-2.5-pro-tts"

    if inp.multi_speaker and inp.speakers and len(inp.speakers) >= 2:
        # Multi-speaker mode - use multiSpeakerMarkup format per Google Cloud TTS API
        # Build speaker voice configs with correct field names
        speaker_voice_configs = []
        for speaker in inp.speakers[:2]:
            speaker_voice_configs.append({
                "speakerAlias": speaker.get("name", "Speaker"),
                "speakerId": speaker.get("voice", "Kore")
            })

        # Parse text to extract turns (format: "SpeakerName: dialogue text")
        turns = []
        lines = inp.text.strip().split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                continue
            # Try to parse "Speaker: text" format
            if ':' in line:
                parts = line.split(':', 1)
                speaker_name = parts[0].strip()
                text_content = parts[1].strip() if len(parts) > 1 else ""
                # Match speaker name to configured speakers
                matched_speaker = None
                for sp in inp.speakers[:2]:
                    if sp.get("name", "").lower() == speaker_name.lower():
                        matched_speaker = sp.get("name")
                        break
                if matched_speaker and text_content:
                    turns.append({
                        "speaker": matched_speaker,
                        "text": text_content
                    })
                elif text_content:
                    # Default to first speaker if no match
                    turns.append({
                        "speaker": inp.speakers[0].get("name", "Speaker1"),
                        "text": line
                    })
            else:
                # No colon, assign to first speaker
                turns.append({
                    "speaker": inp.speakers[0].get("name", "Speaker1"),
                    "text": line
                })

        # Build the correct payload structure for multi-speaker
        payload = {
            "input": {
                "multiSpeakerMarkup": {
                    "turns": turns
                }
            },
            "voice": {
                "languageCode": "en-US",
                "modelName": model_name,
                "multiSpeakerVoiceConfig": {
                    "speakerVoiceConfigs": speaker_voice_configs
                }
            },
            "audioConfig": {
                "audioEncoding": "LINEAR16",
                "sampleRateHertz": 24000
            }
        }
        print(f"[Gemini TTS Cloud GA] Multi-speaker mode: {len(speaker_voice_configs)} speakers, {len(turns)} turns")
    else:
        # Single-speaker mode
        voice_name = inp.voice_name or "Kore"
        payload = {
            "input": {
                "text": inp.text
            },
            "voice": {
                "languageCode": "en-US",
                "name": voice_name,
                "modelName": model_name
            },
            "audioConfig": {
                "audioEncoding": "LINEAR16",
                "sampleRateHertz": 24000
            }
        }
        print(f"[Gemini TTS Cloud GA] Single-speaker mode: {voice_name} (model: {model_name})")

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json"
    }

    try:
        print(f"[Gemini TTS Cloud GA] Calling Cloud TTS API with model: {model_name}")
        print(f"[Gemini TTS Cloud GA] URL: {CLOUD_TTS_URL}")
        print(f"[Gemini TTS Cloud GA] Payload: {json.dumps(payload, indent=2)}")
        response = requests.post(CLOUD_TTS_URL, json=payload, headers=headers, timeout=400)
        print(f"[Gemini TTS Cloud GA] Response status: {response.status_code}")
        if response.status_code != 200:
            print(f"[Gemini TTS Cloud GA] Response body: {response.text[:500]}")
        response.raise_for_status()
        data = response.json()

        # Cloud TTS returns base64 audio in audioContent field
        audio_content_b64 = data.get("audioContent")
        if not audio_content_b64:
            raise HTTPException(status_code=500, detail="No audio content in Cloud TTS response")

        audio_data = base64.b64decode(audio_content_b64)

        # LINEAR16 is already PCM, convert to WAV
        sample_rate = 24000
        sample_width = 2  # 16-bit
        num_channels = 1  # Mono

        wav_bytes = pcm_to_wav(audio_data, sample_width, sample_rate, num_channels)
        print(f"[Gemini TTS Cloud GA] Successfully generated {len(wav_bytes)} bytes of audio")
        return wav_bytes

    except requests.exceptions.RequestException as e:
        error_detail = str(e)
        try:
            error_detail = e.response.json().get("error", {}).get("message", e.response.text)
        except Exception:
            pass
        print(f"ERROR: Cloud TTS API error: {error_detail}")
        raise HTTPException(status_code=e.response.status_code if e.response else 502, detail=f"Cloud TTS API error: {error_detail}")
    except Exception as e:
        print(f"ERROR: Cloud TTS audio conversion failed: {e}")
        raise HTTPException(status_code=500, detail=f"Cloud TTS audio conversion failed: {e}")


def call_gemini_tts_preview(inp: GeminiProTTSIn) -> bytes:
    """Calls Gemini TTS via AI Studio API (simple API key) with preview models."""
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=400, detail="GOOGLE_API_KEY not configured.")

    # Map GA model names to preview model names
    model_mapping = {
        "gemini-2.5-pro-tts": "gemini-2.5-pro-preview-tts",
        "gemini-2.5-flash-tts": "gemini-2.5-flash-preview-tts"
    }
    preview_model = model_mapping.get(inp.model, "gemini-2.5-pro-preview-tts")

    # Use Gemini AI Studio API endpoint
    url = f"{GEMINI_BASE_URL}/{preview_model}:generateContent?key={GOOGLE_API_KEY}"

    # Build speech configuration based on mode
    speech_config = {}

    if inp.multi_speaker and inp.speakers and len(inp.speakers) >= 2:
        # Multi-speaker mode
        speaker_voice_configs = []
        for speaker in inp.speakers[:2]:
            speaker_voice_configs.append({
                "speaker": speaker.get("name", "Speaker"),
                "voiceConfig": {
                    "prebuiltVoiceConfig": {
                        "voiceName": speaker.get("voice", "Kore")
                    }
                }
            })

        speech_config = {
            "multiSpeakerVoiceConfig": {
                "speakerVoiceConfigs": speaker_voice_configs
            }
        }
        print(f"[Gemini TTS] Multi-speaker mode: {len(speaker_voice_configs)} speakers configured")
    else:
        # Single-speaker mode
        voice_name = inp.voice_name or "Kore"
        speech_config = {
            "voiceConfig": {
                "prebuiltVoiceConfig": {
                    "voiceName": voice_name
                }
            }
        }
        print(f"[Gemini TTS Preview] Single-speaker mode: {voice_name} (model: {preview_model})")

    payload = {
        "contents": [{
           "parts": [{ "text": inp.text }]
        }],
        "generationConfig": {
            "responseModalities": ["AUDIO"],
            "speechConfig": speech_config
        },
        "model": preview_model
    }

    try:
        response = requests.post(url, json=payload, timeout=400)
        response.raise_for_status()
        data = response.json()

        part = data.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0]
        audio_data_b64 = part.get("inlineData", {}).get("data")
        mime_type = part.get("inlineData", {}).get("mimeType", "audio/L16")

        if not audio_data_b64:
            raise HTTPException(status_code=500, detail="No audio data in Gemini response.")

        audio_data = base64.b64decode(audio_data_b64)

        # Extract sample rate from mime type, default 24000
        sample_rate = 24000
        if "rate=" in mime_type:
            try:
                sample_rate = int(mime_type.split("rate=")[1].split(";")[0])
            except Exception:
                pass

        # Gemini TTS returns s16le (signed 16-bit, little-endian)
        sample_width = 2  # 16 bits = 2 bytes
        num_channels = 1  # Mono

        # Convert PCM to WAV
        wav_bytes = pcm_to_wav(audio_data, sample_width, sample_rate, num_channels)
        return wav_bytes

    except requests.exceptions.RequestException as e:
        error_detail = str(e)
        try:
            error_detail = e.response.json().get("error", {}).get("message", e.response.text)
        except Exception:
            pass
        print(f"ERROR: Gemini Pro TTS API error: {error_detail}")
        raise HTTPException(status_code=e.response.status_code if e.response else 502, detail=f"Gemini Pro TTS API error: {error_detail}")
    except Exception as e:
        print(f"ERROR: Gemini Pro TTS audio conversion failed: {e}")
        raise HTTPException(status_code=500, detail=f"Audio conversion failed: {e}")


def call_gemini_tts(inp: GeminiProTTSIn) -> bytes:
    """Router function that chooses between Cloud TTS (GA) and AI Studio (Preview).
    - If GOOGLE_APPLICATION_CREDENTIALS is set and valid: Use Cloud TTS API with GA models
    - Otherwise: Fall back to AI Studio API with preview models
    """
    # Scrub non-spoken symbols; parenthetical emotional cues '(frantically)' are preserved.
    try:
        if getattr(inp, "text", None):
            inp.text = sanitize_for_speech(inp.text)
    except Exception:
        pass
    if USE_CLOUD_TTS and GOOGLE_AUTH_AVAILABLE:
        print("[Gemini TTS] Using Cloud TTS API (GA models: gemini-2.5-pro-tts)")
        return call_gemini_tts_cloud(inp)
    else:
        if not USE_CLOUD_TTS:
            print("[Gemini TTS] Using AI Studio API (Preview models) - Set GOOGLE_APPLICATION_CREDENTIALS for GA")
        return call_gemini_tts_preview(inp)


# --- Lyria-002 Music Generation ---
def _get_lyria_project_id() -> str:
    """Extract project ID from service account credentials."""
    if not GOOGLE_APPLICATION_CREDENTIALS:
        raise HTTPException(status_code=400, detail="GOOGLE_APPLICATION_CREDENTIALS not configured")
    try:
        with open(GOOGLE_APPLICATION_CREDENTIALS, 'r') as f:
            creds = json.load(f)
            return creds.get("project_id", "")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read service account: {e}")


def call_lyria_music(inp: LyriaMusicIn) -> list:
    """Generate music using Google Lyria-002 via Vertex AI.
    Returns list of WAV audio bytes (48kHz stereo, 30 seconds each).
    Supports generating 1-4 variations via sample_count parameter.
    Note: seed and sample_count > 1 are mutually exclusive per API spec.
    """
    if not USE_CLOUD_TTS or not GOOGLE_AUTH_AVAILABLE:
        raise HTTPException(
            status_code=400,
            detail="Lyria requires Google Cloud service account. Set GOOGLE_APPLICATION_CREDENTIALS."
        )

    # Get access token using same auth as Cloud TTS
    access_token = _get_cloud_tts_access_token()
    project_id = _get_lyria_project_id()

    if not project_id:
        raise HTTPException(status_code=400, detail="Could not determine project ID from service account")

    # Validate sample_count (1-4)
    sample_count = inp.sample_count if inp.sample_count else 1
    sample_count = max(1, min(4, sample_count))  # Clamp to 1-4

    # Validate mutual exclusivity: seed cannot be used with sample_count > 1
    if inp.seed is not None and sample_count > 1:
        raise HTTPException(
            status_code=400,
            detail="Cannot use seed with sample_count > 1. Use seed for reproducibility OR sample_count for variations, not both."
        )

    # Build the Lyria API URL
    url = LYRIA_MUSIC_URL.format(project_id=project_id)

    # Build request payload
    instance = {"prompt": inp.prompt}
    if inp.negative_prompt:
        instance["negative_prompt"] = inp.negative_prompt
    if inp.seed is not None:
        instance["seed"] = inp.seed

    payload = {
        "instances": [instance],
        "parameters": {
            "sample_count": sample_count
        }
    }

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json"
    }

    print(f"[Lyria] Generating {sample_count} music variation(s): {inp.prompt[:100]}...")
    print(f"[Lyria] URL: {url}")

    try:
        # Increase timeout for multiple samples
        timeout = 120 + (sample_count - 1) * 30  # Extra 30s per additional sample
        response = requests.post(url, headers=headers, json=payload, timeout=timeout)
        print(f"[Lyria] Response status: {response.status_code}")

        if response.status_code != 200:
            error_detail = response.text[:500] if response.text else "Unknown error"
            print(f"[Lyria] Error: {error_detail}")
            # Check for recitation filter
            if "recitation" in error_detail.lower():
                raise HTTPException(
                    status_code=400,
                    detail="Prompt blocked by copyright filter. Try a more original description that doesn't reference specific songs or artists."
                )
            raise HTTPException(status_code=response.status_code, detail=f"Lyria API error: {error_detail}")

        result = response.json()

        # Extract audio content from response
        predictions = result.get("predictions", [])
        if not predictions:
            raise HTTPException(status_code=500, detail="No audio generated by Lyria")

        # Extract all audio samples from predictions
        audio_samples = []
        for i, prediction in enumerate(predictions):
            audio_content_b64 = prediction.get("bytesBase64Encoded", "") or prediction.get("audioContent", "")
            if audio_content_b64:
                wav_bytes = base64.b64decode(audio_content_b64)
                audio_samples.append(wav_bytes)
                print(f"[Lyria] Sample {i+1}: {len(wav_bytes)} bytes")

        if not audio_samples:
            raise HTTPException(status_code=500, detail="No audio content in Lyria response")

        print(f"[Lyria] Generated {len(audio_samples)} audio sample(s)")
        return audio_samples

    except requests.exceptions.Timeout:
        raise HTTPException(status_code=504, detail="Lyria API timeout - music generation took too long")
    except requests.exceptions.RequestException as e:
        raise HTTPException(status_code=502, detail=f"Lyria API request failed: {e}")


@app.post("/generate/lyria_music")
async def generate_lyria_music_async(inp: LyriaMusicIn):
    """Queue Lyria music generation"""
    try:
        # Validate that we have the required credentials
        if not USE_CLOUD_TTS or not GOOGLE_AUTH_AVAILABLE:
            raise HTTPException(
                status_code=400,
                detail="Lyria requires Google Cloud service account. Set GOOGLE_APPLICATION_CREDENTIALS."
            )

        task = create_task(
            TaskType.LYRIA_MUSIC,
            operator=inp.operator,
            prompt=inp.prompt,
            result_data=inp.dict()
        )
        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": "Lyria music generation queued"
        }
    except HTTPException:
        raise
    except Exception as e:
        print(f"ERROR: Failed to queue Lyria music: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/music/status")
async def get_music_status():
    """Check Lyria music generation availability and configuration."""
    return {
        "lyria_available": USE_CLOUD_TTS and GOOGLE_AUTH_AVAILABLE,
        "service_account_configured": bool(GOOGLE_APPLICATION_CREDENTIALS),
        "google_auth_available": GOOGLE_AUTH_AVAILABLE,
        "model": "lyria-002",
        "output_format": "WAV 48kHz stereo",
        "duration": "30 seconds"
    }


@app.post("/generate/elevenlabs_music")
async def generate_elevenlabs_music_async(body: dict = Body(...)):
    """Queue ElevenLabs Music generation (full songs, up to 5 min, w/ vocals).

    A SEPARATE music endpoint from /generate/lyria_music — both coexist
    (provider-explicit naming). Exactly one of ``prompt`` / ``composition_plan``
    is required; the rest (``music_length_ms``, ``force_instrumental``, ``seed``,
    ``operator``) are optional. Returns a task_id — poll get_task_status.
    """
    try:
        prompt = body.get("prompt")
        composition_plan = body.get("composition_plan")
        if (prompt is None) == (composition_plan is None):
            raise HTTPException(
                status_code=400,
                detail="Provide exactly one of `prompt` or `composition_plan`."
            )

        # Persist only the generation params the processor consumes.
        params = {
            "prompt": prompt,
            "composition_plan": composition_plan,
            "music_length_ms": body.get("music_length_ms"),
            "force_instrumental": bool(body.get("force_instrumental", False)),
            "seed": body.get("seed"),
            "operator": body.get("operator"),
        }
        task = create_task(
            TaskType.ELEVENLABS_MUSIC,
            operator=body.get("operator"),
            prompt=prompt,
            result_data=params
        )
        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": "ElevenLabs music generation queued"
        }
    except HTTPException:
        raise
    except Exception as e:
        print(f"ERROR: Failed to queue ElevenLabs music: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/generate/elevenlabs_sound_effect")
async def generate_elevenlabs_sound_effect(body: dict = Body(...)):
    """Generate a sound effect from a text description (ElevenLabs sound-generation).

    SYNCHRONOUS — generation takes only seconds, so this returns the saved audio
    URL directly (no task_id). Body: ``text`` (required), optional
    ``duration_seconds`` (0.1-30), ``prompt_influence`` (0-1), ``loop`` (seamless
    ambience), ``operator``. Saves the mp3 to uploads + indexes it for media tools.
    """
    from Orchestrator.elevenlabs import sfx as el_sfx
    from Orchestrator.media_index import add_media_entry
    from Orchestrator.tasks import generate_prompt_slug

    text = (body.get("text") or "").strip()
    if not text:
        raise HTTPException(status_code=400, detail="`text` is required.")

    try:
        mp3_bytes = el_sfx.generate(
            text,
            duration_seconds=body.get("duration_seconds"),
            prompt_influence=body.get("prompt_influence"),
            loop=bool(body.get("loop", False)),
        )
    except RuntimeError as e:
        raise HTTPException(status_code=502, detail=str(e))
    except Exception as e:
        print(f"ERROR: Failed to generate ElevenLabs sound effect: {e}")
        raise HTTPException(status_code=500, detail=str(e))

    slug = generate_prompt_slug(text)
    filename = f"{slug}_{uuid.uuid4().hex}_sfx.mp3"
    save_path = UPLOADS_DIR / filename
    save_path.write_bytes(mp3_bytes)
    audio_url = f"/ui/uploads/{filename}"
    print(f"[SFX] Saved ElevenLabs sound effect: {filename} ({len(mp3_bytes)} bytes)")

    add_media_entry(
        url=audio_url,
        media_type="audio",
        prompt=text,
        filename=filename,
        file_size=len(mp3_bytes),
        extra_metadata={
            "provider": "elevenlabs",
            "kind": "sound_effect",
            "duration_seconds": body.get("duration_seconds"),
            "loop": bool(body.get("loop", False)),
        },
    )

    return {"status": "success", "audio_url": audio_url, "size_bytes": len(mp3_bytes)}


@app.post("/elevenlabs/voice-changer")
async def elevenlabs_voice_changer(body: dict = Body(...)):
    """Re-voice an existing recording into a target ElevenLabs voice (speech-to-speech).

    SYNCHRONOUS. Body: ``audio_path`` (required, a local/session file),
    ``target_voice`` (required — accepts ``elevenlabs:<id>`` or a raw voice id),
    optional ``output_format``, ``operator``. The original delivery/emotion is
    preserved. Saves the result to uploads + indexes it for media tools.
    """
    from Orchestrator.elevenlabs import transform as el_transform
    from Orchestrator.media_index import add_media_entry

    audio_path = (body.get("audio_path") or "").strip()
    target_voice = (body.get("target_voice") or "").strip()
    if not audio_path:
        raise HTTPException(status_code=400, detail="`audio_path` is required.")
    if not target_voice:
        raise HTTPException(status_code=400, detail="`target_voice` is required.")
    if not os.path.exists(audio_path):
        raise HTTPException(status_code=400, detail=f"Audio file not found: {audio_path}")

    try:
        audio_bytes = el_transform.change_voice(
            audio_path,
            target_voice,
            output_format=body.get("output_format"),
        )
    except RuntimeError as e:
        raise HTTPException(status_code=502, detail=str(e))
    except Exception as e:
        print(f"ERROR: ElevenLabs voice changer failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))

    filename = f"voice_changed_{uuid.uuid4().hex}.mp3"
    save_path = UPLOADS_DIR / filename
    save_path.write_bytes(audio_bytes)
    audio_url = f"/ui/uploads/{filename}"
    print(f"[VOICE-CHANGER] Saved: {filename} ({len(audio_bytes)} bytes)")

    add_media_entry(
        url=audio_url,
        media_type="audio",
        prompt=f"voice-changed -> {target_voice}",
        filename=filename,
        file_size=len(audio_bytes),
        extra_metadata={
            "provider": "elevenlabs",
            "kind": "voice_changer",
            "target_voice": target_voice,
            "source_audio": os.path.basename(audio_path),
        },
    )

    return {"status": "success", "audio_url": audio_url, "size_bytes": len(audio_bytes)}


@app.post("/elevenlabs/isolate")
async def elevenlabs_isolate(body: dict = Body(...)):
    """Strip background noise from a recording, isolating the voice (audio-isolation).

    SYNCHRONOUS. Body: ``audio_path`` (required, a local/session file),
    ``operator`` (optional). Saves the cleaned audio to uploads + indexes it.
    """
    from Orchestrator.elevenlabs import transform as el_transform
    from Orchestrator.media_index import add_media_entry

    audio_path = (body.get("audio_path") or "").strip()
    if not audio_path:
        raise HTTPException(status_code=400, detail="`audio_path` is required.")
    if not os.path.exists(audio_path):
        raise HTTPException(status_code=400, detail=f"Audio file not found: {audio_path}")

    try:
        audio_bytes = el_transform.isolate(audio_path)
    except RuntimeError as e:
        raise HTTPException(status_code=502, detail=str(e))
    except Exception as e:
        print(f"ERROR: ElevenLabs voice isolation failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))

    filename = f"voice_isolated_{uuid.uuid4().hex}.mp3"
    save_path = UPLOADS_DIR / filename
    save_path.write_bytes(audio_bytes)
    audio_url = f"/ui/uploads/{filename}"
    print(f"[ISOLATE] Saved: {filename} ({len(audio_bytes)} bytes)")

    add_media_entry(
        url=audio_url,
        media_type="audio",
        prompt="voice-isolated (background noise removed)",
        filename=filename,
        file_size=len(audio_bytes),
        extra_metadata={
            "provider": "elevenlabs",
            "kind": "voice_isolator",
            "source_audio": os.path.basename(audio_path),
        },
    )

    return {"status": "success", "audio_url": audio_url, "size_bytes": len(audio_bytes)}


@app.post("/generate/gemini_tts")  # Note: renamed from /generate/gemini-tts
async def generate_gemini_tts_async(inp: GeminiProTTSIn):
    """Queue Gemini Pro TTS generation"""
    try:
        task = create_task(
            TaskType.GEMINI_TTS,
            operator=inp.operator,
            result_data=inp.dict()
        )
        return {
            "task_id": task.task_id,
            "status": task.status,
            "message": "Gemini Pro TTS generation queued"
        }
    except Exception as e:
        print(f"ERROR: Failed to queue Gemini Pro TTS: {e}")
        raise HTTPException(status_code=500, detail=str(e))
        
