"""Parity test for the ToolVault v2 tool_registry cutover (Task 4.1).

`golden_tool_schemas.json` is the "before" snapshot: every provider converter's
output, filtered to drop UGV tools and sorted by name, captured while
``tool_registry.TOOL_DEFINITIONS`` was still the giant literal list.

After the cutover (TOOL_DEFINITIONS sourced from ``registry.load_canonical()``),
these tests assert that every provider sees BYTE-IDENTICAL schemas for all
non-UGV tools, that UGV has disappeared from the surface (intended — the module
registry has no ugv tools), and that alias/executor resolution still works.

The golden was generated by ``_capture_golden.py``; regenerate only by
re-running that script against the literal source (which no longer exists after
the cutover — so the golden is effectively frozen).

Task 4.4 — ``x-source: operators``:
The golden was captured BEFORE any module carried ``x-source``, so its
``operator`` fields are plain strings with NO ``enum``. After 4.4 wires
``"x-source": "operators"`` onto every operator-bearing module, the converter
paths (which run ``resolve_schema``) fill that field's ``enum`` from the live
operator list and STRIP the ``x-source`` marker. To prove the change is
SURGICAL — i.e. ONLY the operator enum changed and nothing else drifted — the
parity tests below NORMALIZE the current output (drop the resolver-injected
``enum`` from any property named ``operator``) and assert the normalized output
is byte-identical to the (operator-enum-free) golden. Dedicated tests then
assert the operator enum IS present (filled to a monkeypatched list) and that
the ``x-source`` marker never leaks to any provider.
"""

import json
import sys
import types
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Minimal mcp.types.Tool stub: the real ``mcp`` package is not installed in
# this venv (the MCP server runs in a separate environment), but ``to_mcp``
# lazy-imports ``mcp.types.Tool`` and only reads .name/.description/.inputSchema
# back. Install the shim before importing tool_registry consumers.
# ---------------------------------------------------------------------------
def _install_mcp_stub() -> None:
    if "mcp.types" in sys.modules or "mcp" in sys.modules:
        return
    try:
        import mcp.types  # noqa: F401
        return
    except Exception:
        pass

    class Tool:
        def __init__(self, name, description, inputSchema):
            self.name = name
            self.description = description
            self.inputSchema = inputSchema

    mcp_mod = types.ModuleType("mcp")
    types_mod = types.ModuleType("mcp.types")
    types_mod.Tool = Tool
    mcp_mod.types = types_mod
    sys.modules["mcp"] = mcp_mod
    sys.modules["mcp.types"] = types_mod


_install_mcp_stub()

from Orchestrator.tools import tool_registry as tr  # noqa: E402
from Orchestrator.toolvault import resolvers as tv_resolvers  # noqa: E402

GOLDEN_PATH = Path(__file__).parent / "golden_tool_schemas.json"

# Known operator list the resolver is pinned to for the whole module so the
# operator enum is deterministic regardless of the live USERS_LIST on the box.
FAKE_OPERATORS = ["Brandon", "system"]


@pytest.fixture(autouse=True)
def _pin_operators(monkeypatch):
    """Pin ``resolvers._list_operators`` to a known list for every test.

    The converter paths lazy-import ``resolve_schema`` which calls
    ``_list_operators``; pinning it makes the resolved operator enum
    deterministic (``FAKE_OPERATORS``) and independent of the live backend.
    """
    monkeypatch.setattr(tv_resolvers, "_list_operators", lambda ctx: list(FAKE_OPERATORS))


# ---------------------------------------------------------------------------
# Filters mirror _capture_golden.py exactly (drop ugv_*, sort by name).
# ---------------------------------------------------------------------------
def _is_ugv(name: str) -> bool:
    return name.startswith("ugv_")


def _filter_anthropic(tools):
    return sorted((t for t in tools if not _is_ugv(t["name"])), key=lambda t: t["name"])


def _filter_openai_rest(tools):
    return sorted(
        (t for t in tools if not _is_ugv(t["function"]["name"])),
        key=lambda t: t["function"]["name"],
    )


def _filter_gemini(tools):
    out = []
    for wrapper in tools:
        new_wrapper = dict(wrapper)
        for key in ("function_declarations", "functionDeclarations"):
            if key in new_wrapper:
                new_wrapper[key] = sorted(
                    (d for d in new_wrapper[key] if not _is_ugv(d["name"])),
                    key=lambda d: d["name"],
                )
        out.append(new_wrapper)
    return out


def _mcp_to_dicts(tools):
    return [
        {"name": t.name, "description": t.description, "inputSchema": t.inputSchema}
        for t in tools
    ]


def _roundtrip(obj):
    """JSON round-trip so the comparison is on plain serializable structures,
    identical to how the golden was written (e.g. tuples -> lists)."""
    return json.loads(json.dumps(obj))


# ---------------------------------------------------------------------------
# Operator-enum normalization (Task 4.4).
#
# The golden predates x-source, so its `operator` properties have no `enum`.
# Current output has a resolver-injected `enum` on every property named exactly
# `operator`. Stripping just that key from the current output should make it
# byte-identical to the golden — proving NOTHING ELSE changed.
# ---------------------------------------------------------------------------
def _strip_operator_enums(obj):
    """Recursively drop the `enum` key from any dict property named `operator`.

    Walks every `properties` map (wherever it appears across the provider
    shapes) and, for the `operator` property specifically, removes the injected
    `enum`. Returns a new structure; the input is not mutated.
    """
    if isinstance(obj, list):
        return [_strip_operator_enums(v) for v in obj]
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if k == "properties" and isinstance(v, dict):
                new_props = {}
                for pname, pval in v.items():
                    if pname == "operator" and isinstance(pval, dict):
                        pval = {pk: pv for pk, pv in pval.items() if pk != "enum"}
                    new_props[pname] = _strip_operator_enums(pval)
                out[k] = new_props
            else:
                out[k] = _strip_operator_enums(v)
        return out
    return obj


def _find_xsource_paths(obj, path=""):
    """Return the JSON-ish paths of any surviving `x-source` keys (should be [])."""
    leaks = []
    if isinstance(obj, dict):
        if "x-source" in obj:
            leaks.append(path or "<root>")
        for k, v in obj.items():
            leaks.extend(_find_xsource_paths(v, f"{path}/{k}"))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            leaks.extend(_find_xsource_paths(v, f"{path}[{i}]"))
    return leaks


# Tools that carry an `operator` parameter (operator-bearing modules). Used to
# assert the resolver actually filled an enum where we expect one.
OPERATOR_BEARING = {
    "browse_index",
    "chat_with_context",
    "get_context",
    "gmail_labels",
    "gmail_read",
    "gmail_reply",
    "gmail_search",
    "gmail_send",
    "list_recent_snapshots",
    "mint_snapshot",
    "search_snapshots",
}


def _operator_prop(schema_params):
    """Return the `operator` property dict from a JSON-Schema params object, or None."""
    if not isinstance(schema_params, dict):
        return None
    return schema_params.get("properties", {}).get("operator")


@pytest.fixture(scope="module")
def golden():
    return json.loads(GOLDEN_PATH.read_text())


def _current():
    return {
        "anthropic_chat": _filter_anthropic(tr.get_anthropic_tools("chat")),
        "openai_rest_chat": _filter_openai_rest(tr.get_openai_rest_tools("chat")),
        "gemini_rest_chat": _filter_gemini(tr.get_gemini_rest_tools("chat")),
        "openai_realtime": _filter_anthropic(tr.get_openai_realtime_tools("realtime")),
        "gemini_live": _filter_gemini(tr.get_gemini_live_tools("gemini_live")),
        "mcp": _filter_anthropic(_mcp_to_dicts(tr.get_mcp_tools())),
    }


# ---------------------------------------------------------------------------
# Parity: every format identical to the golden once the resolver-injected
# operator enum is normalized away (non-ugv, name-sorted). This proves the
# x-source change is SURGICAL — the operator enum is the ONLY difference.
# ---------------------------------------------------------------------------
def _names_of(fmt, entries):
    """Set of tool names present in a format's entries (shape-aware)."""
    if fmt in ("gemini_rest_chat", "gemini_live"):
        names = set()
        for wrapper in entries:
            for key in ("function_declarations", "functionDeclarations"):
                for d in wrapper.get(key, []):
                    names.add(d["name"])
        return names
    if fmt == "openai_rest_chat":
        return {t["function"]["name"] for t in entries}
    return {t["name"] for t in entries}  # anthropic, openai_realtime, mcp


def _restrict(fmt, entries, names):
    """Filter entries to only tools whose name is in `names` (shape-preserving, sorted).

    Lets parity ignore NEW tools added after the golden was captured while still
    proving every golden tool is byte-identical.
    """
    if fmt in ("gemini_rest_chat", "gemini_live"):
        out = []
        for wrapper in entries:
            w = dict(wrapper)
            for key in ("function_declarations", "functionDeclarations"):
                if key in w:
                    w[key] = sorted(
                        (d for d in w[key] if d["name"] in names),
                        key=lambda d: d["name"],
                    )
            out.append(w)
        return out
    if fmt == "openai_rest_chat":
        return sorted(
            (t for t in entries if t["function"]["name"] in names),
            key=lambda t: t["function"]["name"],
        )
    return sorted((t for t in entries if t["name"] in names), key=lambda t: t["name"])


@pytest.mark.parametrize(
    "fmt",
    [
        "anthropic_chat",
        "openai_rest_chat",
        "gemini_rest_chat",
        "openai_realtime",
        "gemini_live",
        "mcp",
    ],
)
def test_format_parity(golden, fmt):
    # web_search was intentionally removed by the multi-provider web-search
    # feature (replaced by six per-provider tools); the frozen golden predates
    # that removal, so exclude it from BOTH sides of the parity comparison while
    # still proving every OTHER golden tool is byte-identical.
    intentionally_removed = {"web_search", "generate_image"}
    current = _roundtrip(_current()[fmt])
    # No x-source marker may survive into any provider's output.
    assert _find_xsource_paths(current) == [], f"{fmt} leaked x-source markers"
    normalized = _strip_operator_enums(current)
    golden_names = _names_of(fmt, golden[fmt]) - intentionally_removed
    # No migrated (golden) tool may be LOST (except intentionally-removed ones).
    missing = golden_names - _names_of(fmt, normalized)
    assert not missing, f"{fmt} lost golden tools: {sorted(missing)}"
    # Every remaining golden tool must be byte-identical (modulo operator enum).
    # NEW tools added after the golden capture (e.g. roll_dice) are ignored; the
    # intentionally-removed tool is dropped from the golden side too.
    restricted = _restrict(fmt, normalized, golden_names)
    golden_restricted = _restrict(fmt, golden[fmt], golden_names)
    assert restricted == golden_restricted, f"{fmt} drifted from golden (beyond operator enum)"


def test_all_formats_present_and_nonempty(golden):
    for fmt in (
        "anthropic_chat",
        "openai_rest_chat",
        "gemini_rest_chat",
        "openai_realtime",
        "gemini_live",
        "mcp",
    ):
        assert fmt in golden and golden[fmt], f"golden missing/empty for {fmt}"


# ---------------------------------------------------------------------------
# UGV is gone from the surface (intended — load_canonical has no ugv tools).
# ---------------------------------------------------------------------------
def test_ugv_absent_from_anthropic_chat():
    names = [t["name"] for t in tr.get_anthropic_tools("chat")]
    assert not [n for n in names if n.startswith("ugv_")]


def test_ugv_absent_from_mcp():
    names = [t.name for t in tr.get_mcp_tools()]
    assert not [n for n in names if n.startswith("ugv_")]


# ---------------------------------------------------------------------------
# TOOL_DEFINITIONS: >= 48 canonical non-ugv tools (48 = migration baseline/floor;
# tools get added over time, so this is a floor, not an exact count).
# ---------------------------------------------------------------------------
def test_tool_definitions_baseline_and_no_ugv():
    defs = tr.TOOL_DEFINITIONS
    assert len(defs) >= 48, f"expected >= 48 canonical tools, got {len(defs)}"
    assert not [t for t in defs if t["name"].startswith("ugv_")]


# ---------------------------------------------------------------------------
# Task 4.4 — operator fields resolve live to the (pinned) operator list across
# every provider format, with NO x-source marker surviving.
# ---------------------------------------------------------------------------
def _params_by_name_flat(tools, name_key="name", params_key=None):
    """For flat-list formats (anthropic/openai_realtime): name -> params object."""
    out = {}
    for t in tools:
        out[t[name_key]] = t.get(params_key) if params_key else t
    return out


def test_operator_enum_anthropic():
    tools = {t["name"]: t for t in tr.get_anthropic_tools("chat")}
    present = OPERATOR_BEARING & set(tools)
    assert present, "expected operator-bearing tools in the chat (anthropic) group"
    for name in present:
        op = _operator_prop(tools[name]["input_schema"])
        assert op is not None, f"{name} lost its operator property"
        assert op.get("enum") == FAKE_OPERATORS, f"{name} operator enum not filled"
        assert "x-source" not in op, f"{name} leaked x-source"
        assert op.get("type") == "string", f"{name} operator type changed"


def test_operator_enum_openai_rest():
    tools = {t["function"]["name"]: t for t in tr.get_openai_rest_tools("chat")}
    present = OPERATOR_BEARING & set(tools)
    assert present, "expected operator-bearing tools in the chat (openai_rest) group"
    for name in present:
        op = _operator_prop(tools[name]["function"]["parameters"])
        assert op is not None and op.get("enum") == FAKE_OPERATORS, name
        assert "x-source" not in op, name


def test_operator_enum_openai_realtime():
    # realtime group differs from chat; assert on whatever operator-bearing
    # tools are present in the realtime surface (e.g. search_snapshots).
    tools = {t["name"]: t for t in tr.get_openai_realtime_tools("realtime")}
    present = OPERATOR_BEARING & set(tools)
    assert present, "expected at least one operator-bearing tool in realtime group"
    for name in present:
        op = _operator_prop(tools[name]["parameters"])
        assert op is not None and op.get("enum") == FAKE_OPERATORS, name
        assert "x-source" not in op, name


def test_operator_enum_gemini_rest():
    decls = tr.get_gemini_rest_tools("chat")[0]["function_declarations"]
    tools = {d["name"]: d for d in decls}
    present = OPERATOR_BEARING & set(tools)
    assert present, "expected operator-bearing tools in the chat (gemini_rest) group"
    for name in present:
        op = _operator_prop(tools[name]["parameters"])
        assert op is not None, name
        # Gemini keeps enum on STRING-typed operator and forces type=string.
        assert op.get("enum") == FAKE_OPERATORS, name
        assert op.get("type") == "string", name
        assert "x-source" not in op, name


def test_operator_enum_gemini_live():
    decls = tr.get_gemini_live_tools("gemini_live")[0]["functionDeclarations"]
    tools = {d["name"]: d for d in decls}
    present = OPERATOR_BEARING & set(tools)
    assert present, "expected at least one operator-bearing tool in gemini_live group"
    for name in present:
        op = _operator_prop(tools[name]["parameters"])
        assert op is not None and op.get("enum") == FAKE_OPERATORS, name
        assert "x-source" not in op, name


def test_operator_enum_mcp():
    tools = {t.name: t for t in tr.get_mcp_tools()}
    for name in OPERATOR_BEARING:
        op = _operator_prop(tools[name].inputSchema)
        assert op is not None and op.get("enum") == FAKE_OPERATORS, name
        assert "x-source" not in op, name


# ---------------------------------------------------------------------------
# Task 4.4 — live end-to-end: the chat injector and the MCP getter both
# resolve x-source operator fields (hermetic; operators are pinned by the
# autouse fixture).
# ---------------------------------------------------------------------------
def test_inject_for_prompt_resolves_operator():
    from Orchestrator.toolvault import injector

    # A prompt that should select search_snapshots (memory search).
    formatted, _instructions = injector.inject_for_prompt(
        "search my snapshots memory for past work on the portal",
        "anthropic",
        "chat",
    )
    by_name = {t["name"]: t for t in formatted}
    assert "search_snapshots" in by_name, "injector did not select search_snapshots"
    op = _operator_prop(by_name["search_snapshots"]["input_schema"])
    assert op is not None, "operator property missing after inject"
    assert op.get("enum") == FAKE_OPERATORS, "operator enum not filled by injector"
    assert "x-source" not in op, "injector leaked x-source"
    # And no x-source anywhere in the whole injected payload.
    assert _find_xsource_paths(formatted) == [], "injector leaked x-source somewhere"


def test_get_mcp_tools_resolves_operator():
    tools = {t.name: t for t in tr.get_mcp_tools()}
    op = _operator_prop(tools["search_snapshots"].inputSchema)
    assert op is not None and op.get("enum") == FAKE_OPERATORS
    assert "x-source" not in op
    # No x-source leaked into any MCP tool's input schema.
    leaks = []
    for t in tr.get_mcp_tools():
        leaks.extend(_find_xsource_paths(t.inputSchema, t.name))
    assert leaks == [], f"MCP leaked x-source: {leaks}"


# ---------------------------------------------------------------------------
# Alias / executor resolution still works.
# ---------------------------------------------------------------------------
def test_alias_resolution():
    assert tr.resolve_executor_name("search_snapshots") == "search_memory"
    assert tr.resolve_alias("search_memory") == "search_snapshots"
    by_alias = tr.get_tool_by_name("search_memory")
    assert by_alias is not None
    assert by_alias["name"] == "search_snapshots"
