"""Parity test for the ToolVault v2 tool_registry cutover (Task 4.1).

`golden_tool_schemas.json` is the "before" snapshot: every provider converter's
output, filtered to drop UGV tools and sorted by name, captured while
``tool_registry.TOOL_DEFINITIONS`` was still the giant literal list.

After the cutover (TOOL_DEFINITIONS sourced from ``registry.load_canonical()``),
these tests assert that every provider sees BYTE-IDENTICAL schemas for all
non-UGV tools, that UGV has disappeared from the surface (intended — the module
registry has no ugv tools), and that alias/executor resolution still works.

The golden was generated by ``_capture_golden.py``; regenerate only by
re-running that script against the literal source (which no longer exists after
the cutover — so the golden is effectively frozen).
"""

import json
import sys
import types
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Minimal mcp.types.Tool stub: the real ``mcp`` package is not installed in
# this venv (the MCP server runs in a separate environment), but ``to_mcp``
# lazy-imports ``mcp.types.Tool`` and only reads .name/.description/.inputSchema
# back. Install the shim before importing tool_registry consumers.
# ---------------------------------------------------------------------------
def _install_mcp_stub() -> None:
    if "mcp.types" in sys.modules or "mcp" in sys.modules:
        return
    try:
        import mcp.types  # noqa: F401
        return
    except Exception:
        pass

    class Tool:
        def __init__(self, name, description, inputSchema):
            self.name = name
            self.description = description
            self.inputSchema = inputSchema

    mcp_mod = types.ModuleType("mcp")
    types_mod = types.ModuleType("mcp.types")
    types_mod.Tool = Tool
    mcp_mod.types = types_mod
    sys.modules["mcp"] = mcp_mod
    sys.modules["mcp.types"] = types_mod


_install_mcp_stub()

from Orchestrator.tools import tool_registry as tr  # noqa: E402

GOLDEN_PATH = Path(__file__).parent / "golden_tool_schemas.json"


# ---------------------------------------------------------------------------
# Filters mirror _capture_golden.py exactly (drop ugv_*, sort by name).
# ---------------------------------------------------------------------------
def _is_ugv(name: str) -> bool:
    return name.startswith("ugv_")


def _filter_anthropic(tools):
    return sorted((t for t in tools if not _is_ugv(t["name"])), key=lambda t: t["name"])


def _filter_openai_rest(tools):
    return sorted(
        (t for t in tools if not _is_ugv(t["function"]["name"])),
        key=lambda t: t["function"]["name"],
    )


def _filter_gemini(tools):
    out = []
    for wrapper in tools:
        new_wrapper = dict(wrapper)
        for key in ("function_declarations", "functionDeclarations"):
            if key in new_wrapper:
                new_wrapper[key] = sorted(
                    (d for d in new_wrapper[key] if not _is_ugv(d["name"])),
                    key=lambda d: d["name"],
                )
        out.append(new_wrapper)
    return out


def _mcp_to_dicts(tools):
    return [
        {"name": t.name, "description": t.description, "inputSchema": t.inputSchema}
        for t in tools
    ]


def _roundtrip(obj):
    """JSON round-trip so the comparison is on plain serializable structures,
    identical to how the golden was written (e.g. tuples -> lists)."""
    return json.loads(json.dumps(obj))


@pytest.fixture(scope="module")
def golden():
    return json.loads(GOLDEN_PATH.read_text())


def _current():
    return {
        "anthropic_chat": _filter_anthropic(tr.get_anthropic_tools("chat")),
        "openai_rest_chat": _filter_openai_rest(tr.get_openai_rest_tools("chat")),
        "gemini_rest_chat": _filter_gemini(tr.get_gemini_rest_tools("chat")),
        "openai_realtime": _filter_anthropic(tr.get_openai_realtime_tools("realtime")),
        "gemini_live": _filter_gemini(tr.get_gemini_live_tools("gemini_live")),
        "mcp": _filter_anthropic(_mcp_to_dicts(tr.get_mcp_tools())),
    }


# ---------------------------------------------------------------------------
# Parity: every format identical to the golden (non-ugv, name-sorted).
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    "fmt",
    [
        "anthropic_chat",
        "openai_rest_chat",
        "gemini_rest_chat",
        "openai_realtime",
        "gemini_live",
        "mcp",
    ],
)
def test_format_parity(golden, fmt):
    current = _roundtrip(_current()[fmt])
    assert current == golden[fmt], f"{fmt} drifted from golden"


def test_all_formats_present_and_nonempty(golden):
    for fmt in (
        "anthropic_chat",
        "openai_rest_chat",
        "gemini_rest_chat",
        "openai_realtime",
        "gemini_live",
        "mcp",
    ):
        assert fmt in golden and golden[fmt], f"golden missing/empty for {fmt}"


# ---------------------------------------------------------------------------
# UGV is gone from the surface (intended — load_canonical has no ugv tools).
# ---------------------------------------------------------------------------
def test_ugv_absent_from_anthropic_chat():
    names = [t["name"] for t in tr.get_anthropic_tools("chat")]
    assert not [n for n in names if n.startswith("ugv_")]


def test_ugv_absent_from_mcp():
    names = [t.name for t in tr.get_mcp_tools()]
    assert not [n for n in names if n.startswith("ugv_")]


# ---------------------------------------------------------------------------
# TOOL_DEFINITIONS now == 48 canonical, non-ugv tools.
# ---------------------------------------------------------------------------
def test_tool_definitions_count_and_no_ugv():
    defs = tr.TOOL_DEFINITIONS
    assert len(defs) == 48, f"expected 48 canonical tools, got {len(defs)}"
    assert not [t for t in defs if t["name"].startswith("ugv_")]


# ---------------------------------------------------------------------------
# Alias / executor resolution still works.
# ---------------------------------------------------------------------------
def test_alias_resolution():
    assert tr.resolve_executor_name("search_snapshots") == "search_memory"
    assert tr.resolve_alias("search_memory") == "search_snapshots"
    by_alias = tr.get_tool_by_name("search_memory")
    assert by_alias is not None
    assert by_alias["name"] == "search_snapshots"
