#!/usr/bin/env bash
# blackbox-status — quick service health snapshot for operators + support.
#
# Tracked in git (was previously generated by install.sh's Step 4d into
# $BLACKBOX_ROOT at install time, which produced an untracked file that
# could collide with future repo content per audit M3). Now install.sh
# just copies (or symlinks) this file into $BLACKBOX_ROOT so customers
# can invoke `./blackbox-status.sh` from anywhere they expect it.

echo "=== BlackBox Service ==="
systemctl status blackbox.service --no-pager | head -15
echo
echo "=== Recent Logs ==="
journalctl -u blackbox.service -n 20 --no-pager
echo
echo "=== Health ==="
curl -fsS http://localhost:9091/health 2>&1 | head -5
